package com.yongche.yopsaas.db.domain;

import java.util.ArrayList;
import java.util.List;

public class YopsaasRideOrderDispatchExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public YopsaasRideOrderDispatchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public YopsaasRideOrderDispatchExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public YopsaasRideOrderDispatchExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        YopsaasRideOrderDispatchExample example = new YopsaasRideOrderDispatchExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public YopsaasRideOrderDispatchExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public YopsaasRideOrderDispatchExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRideOrderDispatchIdIsNull() {
            addCriterion("ride_order_dispatch_id is null");
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdIsNotNull() {
            addCriterion("ride_order_dispatch_id is not null");
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdEqualTo(Long value) {
            addCriterion("ride_order_dispatch_id =", value, "rideOrderDispatchId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderDispatchIdEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_dispatch_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdNotEqualTo(Long value) {
            addCriterion("ride_order_dispatch_id <>", value, "rideOrderDispatchId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderDispatchIdNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_dispatch_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdGreaterThan(Long value) {
            addCriterion("ride_order_dispatch_id >", value, "rideOrderDispatchId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderDispatchIdGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_dispatch_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ride_order_dispatch_id >=", value, "rideOrderDispatchId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderDispatchIdGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_dispatch_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdLessThan(Long value) {
            addCriterion("ride_order_dispatch_id <", value, "rideOrderDispatchId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderDispatchIdLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_dispatch_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdLessThanOrEqualTo(Long value) {
            addCriterion("ride_order_dispatch_id <=", value, "rideOrderDispatchId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderDispatchIdLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_dispatch_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdIn(List<Long> values) {
            addCriterion("ride_order_dispatch_id in", values, "rideOrderDispatchId");
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdNotIn(List<Long> values) {
            addCriterion("ride_order_dispatch_id not in", values, "rideOrderDispatchId");
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdBetween(Long value1, Long value2) {
            addCriterion("ride_order_dispatch_id between", value1, value2, "rideOrderDispatchId");
            return (Criteria) this;
        }

        public Criteria andRideOrderDispatchIdNotBetween(Long value1, Long value2) {
            addCriterion("ride_order_dispatch_id not between", value1, value2, "rideOrderDispatchId");
            return (Criteria) this;
        }

        public Criteria andRideOrderIdIsNull() {
            addCriterion("ride_order_id is null");
            return (Criteria) this;
        }

        public Criteria andRideOrderIdIsNotNull() {
            addCriterion("ride_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andRideOrderIdEqualTo(Long value) {
            addCriterion("ride_order_id =", value, "rideOrderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderIdEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderIdNotEqualTo(Long value) {
            addCriterion("ride_order_id <>", value, "rideOrderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderIdNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderIdGreaterThan(Long value) {
            addCriterion("ride_order_id >", value, "rideOrderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderIdGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ride_order_id >=", value, "rideOrderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderIdGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderIdLessThan(Long value) {
            addCriterion("ride_order_id <", value, "rideOrderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderIdLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("ride_order_id <=", value, "rideOrderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andRideOrderIdLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("ride_order_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRideOrderIdIn(List<Long> values) {
            addCriterion("ride_order_id in", values, "rideOrderId");
            return (Criteria) this;
        }

        public Criteria andRideOrderIdNotIn(List<Long> values) {
            addCriterion("ride_order_id not in", values, "rideOrderId");
            return (Criteria) this;
        }

        public Criteria andRideOrderIdBetween(Long value1, Long value2) {
            addCriterion("ride_order_id between", value1, value2, "rideOrderId");
            return (Criteria) this;
        }

        public Criteria andRideOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("ride_order_id not between", value1, value2, "rideOrderId");
            return (Criteria) this;
        }

        public Criteria andDriverIdIsNull() {
            addCriterion("driver_id is null");
            return (Criteria) this;
        }

        public Criteria andDriverIdIsNotNull() {
            addCriterion("driver_id is not null");
            return (Criteria) this;
        }

        public Criteria andDriverIdEqualTo(Integer value) {
            addCriterion("driver_id =", value, "driverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andDriverIdEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("driver_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDriverIdNotEqualTo(Integer value) {
            addCriterion("driver_id <>", value, "driverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andDriverIdNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("driver_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDriverIdGreaterThan(Integer value) {
            addCriterion("driver_id >", value, "driverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andDriverIdGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("driver_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDriverIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("driver_id >=", value, "driverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andDriverIdGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("driver_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDriverIdLessThan(Integer value) {
            addCriterion("driver_id <", value, "driverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andDriverIdLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("driver_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDriverIdLessThanOrEqualTo(Integer value) {
            addCriterion("driver_id <=", value, "driverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andDriverIdLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("driver_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDriverIdIn(List<Integer> values) {
            addCriterion("driver_id in", values, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotIn(List<Integer> values) {
            addCriterion("driver_id not in", values, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdBetween(Integer value1, Integer value2) {
            addCriterion("driver_id between", value1, value2, "driverId");
            return (Criteria) this;
        }

        public Criteria andDriverIdNotBetween(Integer value1, Integer value2) {
            addCriterion("driver_id not between", value1, value2, "driverId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andNameEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`name` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andNameNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`name` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andNameGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`name` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andNameGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`name` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andNameLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`name` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andNameLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`name` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andScoreEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("score = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andScoreNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("score <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andScoreGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("score > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andScoreGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("score >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andScoreLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("score < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andScoreLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("score <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateIsNull() {
            addCriterion("good_comment_rate is null");
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateIsNotNull() {
            addCriterion("good_comment_rate is not null");
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateEqualTo(Integer value) {
            addCriterion("good_comment_rate =", value, "goodCommentRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andGoodCommentRateEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("good_comment_rate = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateNotEqualTo(Integer value) {
            addCriterion("good_comment_rate <>", value, "goodCommentRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andGoodCommentRateNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("good_comment_rate <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateGreaterThan(Integer value) {
            addCriterion("good_comment_rate >", value, "goodCommentRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andGoodCommentRateGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("good_comment_rate > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("good_comment_rate >=", value, "goodCommentRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andGoodCommentRateGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("good_comment_rate >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateLessThan(Integer value) {
            addCriterion("good_comment_rate <", value, "goodCommentRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andGoodCommentRateLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("good_comment_rate < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateLessThanOrEqualTo(Integer value) {
            addCriterion("good_comment_rate <=", value, "goodCommentRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andGoodCommentRateLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("good_comment_rate <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateIn(List<Integer> values) {
            addCriterion("good_comment_rate in", values, "goodCommentRate");
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateNotIn(List<Integer> values) {
            addCriterion("good_comment_rate not in", values, "goodCommentRate");
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateBetween(Integer value1, Integer value2) {
            addCriterion("good_comment_rate between", value1, value2, "goodCommentRate");
            return (Criteria) this;
        }

        public Criteria andGoodCommentRateNotBetween(Integer value1, Integer value2) {
            addCriterion("good_comment_rate not between", value1, value2, "goodCommentRate");
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountIsNull() {
            addCriterion("unittime_complete_count is null");
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountIsNotNull() {
            addCriterion("unittime_complete_count is not null");
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountEqualTo(Integer value) {
            addCriterion("unittime_complete_count =", value, "unittimeCompleteCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andUnittimeCompleteCountEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("unittime_complete_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountNotEqualTo(Integer value) {
            addCriterion("unittime_complete_count <>", value, "unittimeCompleteCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andUnittimeCompleteCountNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("unittime_complete_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountGreaterThan(Integer value) {
            addCriterion("unittime_complete_count >", value, "unittimeCompleteCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andUnittimeCompleteCountGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("unittime_complete_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("unittime_complete_count >=", value, "unittimeCompleteCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andUnittimeCompleteCountGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("unittime_complete_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountLessThan(Integer value) {
            addCriterion("unittime_complete_count <", value, "unittimeCompleteCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andUnittimeCompleteCountLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("unittime_complete_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountLessThanOrEqualTo(Integer value) {
            addCriterion("unittime_complete_count <=", value, "unittimeCompleteCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andUnittimeCompleteCountLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("unittime_complete_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountIn(List<Integer> values) {
            addCriterion("unittime_complete_count in", values, "unittimeCompleteCount");
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountNotIn(List<Integer> values) {
            addCriterion("unittime_complete_count not in", values, "unittimeCompleteCount");
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountBetween(Integer value1, Integer value2) {
            addCriterion("unittime_complete_count between", value1, value2, "unittimeCompleteCount");
            return (Criteria) this;
        }

        public Criteria andUnittimeCompleteCountNotBetween(Integer value1, Integer value2) {
            addCriterion("unittime_complete_count not between", value1, value2, "unittimeCompleteCount");
            return (Criteria) this;
        }

        public Criteria andIsServedIsNull() {
            addCriterion("is_served is null");
            return (Criteria) this;
        }

        public Criteria andIsServedIsNotNull() {
            addCriterion("is_served is not null");
            return (Criteria) this;
        }

        public Criteria andIsServedEqualTo(Short value) {
            addCriterion("is_served =", value, "isServed");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsServedEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_served = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsServedNotEqualTo(Short value) {
            addCriterion("is_served <>", value, "isServed");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsServedNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_served <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsServedGreaterThan(Short value) {
            addCriterion("is_served >", value, "isServed");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsServedGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_served > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsServedGreaterThanOrEqualTo(Short value) {
            addCriterion("is_served >=", value, "isServed");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsServedGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_served >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsServedLessThan(Short value) {
            addCriterion("is_served <", value, "isServed");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsServedLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_served < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsServedLessThanOrEqualTo(Short value) {
            addCriterion("is_served <=", value, "isServed");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsServedLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_served <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsServedIn(List<Short> values) {
            addCriterion("is_served in", values, "isServed");
            return (Criteria) this;
        }

        public Criteria andIsServedNotIn(List<Short> values) {
            addCriterion("is_served not in", values, "isServed");
            return (Criteria) this;
        }

        public Criteria andIsServedBetween(Short value1, Short value2) {
            addCriterion("is_served between", value1, value2, "isServed");
            return (Criteria) this;
        }

        public Criteria andIsServedNotBetween(Short value1, Short value2) {
            addCriterion("is_served not between", value1, value2, "isServed");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLatitudeEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("latitude = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLatitudeNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("latitude <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLatitudeGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("latitude > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLatitudeGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("latitude >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLatitudeLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("latitude < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLatitudeLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("latitude <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLongitudeEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("longitude = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLongitudeNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("longitude <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLongitudeGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("longitude > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLongitudeGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("longitude >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLongitudeLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("longitude < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andLongitudeLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("longitude <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andBrandIsNull() {
            addCriterion("brand is null");
            return (Criteria) this;
        }

        public Criteria andBrandIsNotNull() {
            addCriterion("brand is not null");
            return (Criteria) this;
        }

        public Criteria andBrandEqualTo(String value) {
            addCriterion("brand =", value, "brand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andBrandEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("brand = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBrandNotEqualTo(String value) {
            addCriterion("brand <>", value, "brand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andBrandNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("brand <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThan(String value) {
            addCriterion("brand >", value, "brand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andBrandGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("brand > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThanOrEqualTo(String value) {
            addCriterion("brand >=", value, "brand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andBrandGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("brand >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBrandLessThan(String value) {
            addCriterion("brand <", value, "brand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andBrandLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("brand < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBrandLessThanOrEqualTo(String value) {
            addCriterion("brand <=", value, "brand");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andBrandLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("brand <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBrandLike(String value) {
            addCriterion("brand like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotLike(String value) {
            addCriterion("brand not like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandIn(List<String> values) {
            addCriterion("brand in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotIn(List<String> values) {
            addCriterion("brand not in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandBetween(String value1, String value2) {
            addCriterion("brand between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotBetween(String value1, String value2) {
            addCriterion("brand not between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNull() {
            addCriterion("car_type is null");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNotNull() {
            addCriterion("car_type is not null");
            return (Criteria) this;
        }

        public Criteria andCarTypeEqualTo(String value) {
            addCriterion("car_type =", value, "carType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeNotEqualTo(String value) {
            addCriterion("car_type <>", value, "carType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThan(String value) {
            addCriterion("car_type >", value, "carType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThanOrEqualTo(String value) {
            addCriterion("car_type >=", value, "carType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThan(String value) {
            addCriterion("car_type <", value, "carType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThanOrEqualTo(String value) {
            addCriterion("car_type <=", value, "carType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeLike(String value) {
            addCriterion("car_type like", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotLike(String value) {
            addCriterion("car_type not like", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeIn(List<String> values) {
            addCriterion("car_type in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotIn(List<String> values) {
            addCriterion("car_type not in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeBetween(String value1, String value2) {
            addCriterion("car_type between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotBetween(String value1, String value2) {
            addCriterion("car_type not between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdIsNull() {
            addCriterion("car_type_id is null");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdIsNotNull() {
            addCriterion("car_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdEqualTo(Integer value) {
            addCriterion("car_type_id =", value, "carTypeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeIdEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeIdNotEqualTo(Integer value) {
            addCriterion("car_type_id <>", value, "carTypeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeIdNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeIdGreaterThan(Integer value) {
            addCriterion("car_type_id >", value, "carTypeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeIdGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_type_id >=", value, "carTypeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeIdGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeIdLessThan(Integer value) {
            addCriterion("car_type_id <", value, "carTypeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeIdLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("car_type_id <=", value, "carTypeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCarTypeIdLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("car_type_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCarTypeIdIn(List<Integer> values) {
            addCriterion("car_type_id in", values, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdNotIn(List<Integer> values) {
            addCriterion("car_type_id not in", values, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("car_type_id between", value1, value2, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("car_type_id not between", value1, value2, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIsNull() {
            addCriterion("is_default is null");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIsNotNull() {
            addCriterion("is_default is not null");
            return (Criteria) this;
        }

        public Criteria andIsDefaultEqualTo(Short value) {
            addCriterion("is_default =", value, "isDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsDefaultEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_default = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotEqualTo(Short value) {
            addCriterion("is_default <>", value, "isDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsDefaultNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_default <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsDefaultGreaterThan(Short value) {
            addCriterion("is_default >", value, "isDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsDefaultGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_default > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsDefaultGreaterThanOrEqualTo(Short value) {
            addCriterion("is_default >=", value, "isDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsDefaultGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_default >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsDefaultLessThan(Short value) {
            addCriterion("is_default <", value, "isDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsDefaultLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_default < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsDefaultLessThanOrEqualTo(Short value) {
            addCriterion("is_default <=", value, "isDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andIsDefaultLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("is_default <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIsDefaultIn(List<Short> values) {
            addCriterion("is_default in", values, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotIn(List<Short> values) {
            addCriterion("is_default not in", values, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultBetween(Short value1, Short value2) {
            addCriterion("is_default between", value1, value2, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotBetween(Short value1, Short value2) {
            addCriterion("is_default not between", value1, value2, "isDefault");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNull() {
            addCriterion("photo is null");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNotNull() {
            addCriterion("photo is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoEqualTo(String value) {
            addCriterion("photo =", value, "photo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andPhotoEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("photo = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPhotoNotEqualTo(String value) {
            addCriterion("photo <>", value, "photo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andPhotoNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("photo <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThan(String value) {
            addCriterion("photo >", value, "photo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andPhotoGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("photo > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("photo >=", value, "photo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andPhotoGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("photo >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPhotoLessThan(String value) {
            addCriterion("photo <", value, "photo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andPhotoLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("photo < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPhotoLessThanOrEqualTo(String value) {
            addCriterion("photo <=", value, "photo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andPhotoLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("photo <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPhotoLike(String value) {
            addCriterion("photo like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotLike(String value) {
            addCriterion("photo not like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoIn(List<String> values) {
            addCriterion("photo in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotIn(List<String> values) {
            addCriterion("photo not in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoBetween(String value1, String value2) {
            addCriterion("photo between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotBetween(String value1, String value2) {
            addCriterion("photo not between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andStatusEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`status` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andStatusNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`status` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`status` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`status` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`status` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("`status` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeNotEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(YopsaasRideOrderDispatch.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        private YopsaasRideOrderDispatchExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        protected Criteria(YopsaasRideOrderDispatchExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public YopsaasRideOrderDispatchExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table yopsaas_ride_order_dispatch
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        void example(com.yongche.yopsaas.db.domain.YopsaasRideOrderDispatchExample example);
    }
}