package com.yongche.yopsaas.db.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class YopsaasRideOrderExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.ride_order_id
     *
     * @mbg.generated
     */
    private Long rideOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.operator_id
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.user_type
     *
     * @mbg.generated
     */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.sms
     *
     * @mbg.generated
     */
    private Integer sms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.create_order_longitude
     *
     * @mbg.generated
     */
    private Double createOrderLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.create_order_latitude
     *
     * @mbg.generated
     */
    private Double createOrderLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.confirm_latitude
     *
     * @mbg.generated
     */
    private Double confirmLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.confirm_longitude
     *
     * @mbg.generated
     */
    private Double confirmLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.arrive_latitude
     *
     * @mbg.generated
     */
    private Double arriveLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.arrive_longitude
     *
     * @mbg.generated
     */
    private Double arriveLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.src_city_name
     *
     * @mbg.generated
     */
    private String srcCityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.dst_city_name
     *
     * @mbg.generated
     */
    private String dstCityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.change_driver_reason_id
     *
     * @mbg.generated
     */
    private Integer changeDriverReasonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.before_cancel_status
     *
     * @mbg.generated
     */
    private Byte beforeCancelStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.app_version
     *
     * @mbg.generated
     */
    private String appVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.driver_version
     *
     * @mbg.generated
     */
    private String driverVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.balance_time
     *
     * @mbg.generated
     */
    private Integer balanceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.balance_result
     *
     * @mbg.generated
     */
    private Byte balanceResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.preauth_status
     *
     * @mbg.generated
     */
    private Byte preauthStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.extra_amount
     *
     * @mbg.generated
     */
    private BigDecimal extraAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.predict_amount
     *
     * @mbg.generated
     */
    private BigDecimal predictAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.night_amount
     *
     * @mbg.generated
     */
    private BigDecimal nightAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.driver_amount
     *
     * @mbg.generated
     */
    private BigDecimal driverAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.predict_origin_amount
     *
     * @mbg.generated
     */
    private BigDecimal predictOriginAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.predict_pay_amount
     *
     * @mbg.generated
     */
    private BigDecimal predictPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.additional_time_amount
     *
     * @mbg.generated
     */
    private BigDecimal additionalTimeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.highway_amount
     *
     * @mbg.generated
     */
    private BigDecimal highwayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.parking_amount
     *
     * @mbg.generated
     */
    private BigDecimal parkingAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.addons_amount
     *
     * @mbg.generated
     */
    private BigDecimal addonsAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.addons_amount_src
     *
     * @mbg.generated
     */
    private String addonsAmountSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.other_amount
     *
     * @mbg.generated
     */
    private BigDecimal otherAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.runtime
     *
     * @mbg.generated
     */
    private Integer runtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.total_distance
     *
     * @mbg.generated
     */
    private Integer totalDistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.deadhead_distance
     *
     * @mbg.generated
     */
    private Integer deadheadDistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.is_night
     *
     * @mbg.generated
     */
    private Byte isNight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.regulatepan_amount
     *
     * @mbg.generated
     */
    private BigDecimal regulatepanAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.regulatedri_amount
     *
     * @mbg.generated
     */
    private BigDecimal regulatedriAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.regulatepan_reason
     *
     * @mbg.generated
     */
    private String regulatepanReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.regulatedri_reason
     *
     * @mbg.generated
     */
    private String regulatedriReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.regulate_amount
     *
     * @mbg.generated
     */
    private BigDecimal regulateAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.estimate_snap
     *
     * @mbg.generated
     */
    private String estimateSnap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.order_port
     *
     * @mbg.generated
     */
    private Integer orderPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.update_time
     *
     * @mbg.generated
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.ride_order_id
     *
     * @return the value of yopsaas_ride_order_ext.ride_order_id
     *
     * @mbg.generated
     */
    public Long getRideOrderId() {
        return rideOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.ride_order_id
     *
     * @param rideOrderId the value for yopsaas_ride_order_ext.ride_order_id
     *
     * @mbg.generated
     */
    public void setRideOrderId(Long rideOrderId) {
        this.rideOrderId = rideOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.operator_id
     *
     * @return the value of yopsaas_ride_order_ext.operator_id
     *
     * @mbg.generated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.operator_id
     *
     * @param operatorId the value for yopsaas_ride_order_ext.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.user_type
     *
     * @return the value of yopsaas_ride_order_ext.user_type
     *
     * @mbg.generated
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.user_type
     *
     * @param userType the value for yopsaas_ride_order_ext.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.sms
     *
     * @return the value of yopsaas_ride_order_ext.sms
     *
     * @mbg.generated
     */
    public Integer getSms() {
        return sms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.sms
     *
     * @param sms the value for yopsaas_ride_order_ext.sms
     *
     * @mbg.generated
     */
    public void setSms(Integer sms) {
        this.sms = sms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.create_order_longitude
     *
     * @return the value of yopsaas_ride_order_ext.create_order_longitude
     *
     * @mbg.generated
     */
    public Double getCreateOrderLongitude() {
        return createOrderLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.create_order_longitude
     *
     * @param createOrderLongitude the value for yopsaas_ride_order_ext.create_order_longitude
     *
     * @mbg.generated
     */
    public void setCreateOrderLongitude(Double createOrderLongitude) {
        this.createOrderLongitude = createOrderLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.create_order_latitude
     *
     * @return the value of yopsaas_ride_order_ext.create_order_latitude
     *
     * @mbg.generated
     */
    public Double getCreateOrderLatitude() {
        return createOrderLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.create_order_latitude
     *
     * @param createOrderLatitude the value for yopsaas_ride_order_ext.create_order_latitude
     *
     * @mbg.generated
     */
    public void setCreateOrderLatitude(Double createOrderLatitude) {
        this.createOrderLatitude = createOrderLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.confirm_latitude
     *
     * @return the value of yopsaas_ride_order_ext.confirm_latitude
     *
     * @mbg.generated
     */
    public Double getConfirmLatitude() {
        return confirmLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.confirm_latitude
     *
     * @param confirmLatitude the value for yopsaas_ride_order_ext.confirm_latitude
     *
     * @mbg.generated
     */
    public void setConfirmLatitude(Double confirmLatitude) {
        this.confirmLatitude = confirmLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.confirm_longitude
     *
     * @return the value of yopsaas_ride_order_ext.confirm_longitude
     *
     * @mbg.generated
     */
    public Double getConfirmLongitude() {
        return confirmLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.confirm_longitude
     *
     * @param confirmLongitude the value for yopsaas_ride_order_ext.confirm_longitude
     *
     * @mbg.generated
     */
    public void setConfirmLongitude(Double confirmLongitude) {
        this.confirmLongitude = confirmLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.arrive_latitude
     *
     * @return the value of yopsaas_ride_order_ext.arrive_latitude
     *
     * @mbg.generated
     */
    public Double getArriveLatitude() {
        return arriveLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.arrive_latitude
     *
     * @param arriveLatitude the value for yopsaas_ride_order_ext.arrive_latitude
     *
     * @mbg.generated
     */
    public void setArriveLatitude(Double arriveLatitude) {
        this.arriveLatitude = arriveLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.arrive_longitude
     *
     * @return the value of yopsaas_ride_order_ext.arrive_longitude
     *
     * @mbg.generated
     */
    public Double getArriveLongitude() {
        return arriveLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.arrive_longitude
     *
     * @param arriveLongitude the value for yopsaas_ride_order_ext.arrive_longitude
     *
     * @mbg.generated
     */
    public void setArriveLongitude(Double arriveLongitude) {
        this.arriveLongitude = arriveLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.src_city_name
     *
     * @return the value of yopsaas_ride_order_ext.src_city_name
     *
     * @mbg.generated
     */
    public String getSrcCityName() {
        return srcCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.src_city_name
     *
     * @param srcCityName the value for yopsaas_ride_order_ext.src_city_name
     *
     * @mbg.generated
     */
    public void setSrcCityName(String srcCityName) {
        this.srcCityName = srcCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.dst_city_name
     *
     * @return the value of yopsaas_ride_order_ext.dst_city_name
     *
     * @mbg.generated
     */
    public String getDstCityName() {
        return dstCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.dst_city_name
     *
     * @param dstCityName the value for yopsaas_ride_order_ext.dst_city_name
     *
     * @mbg.generated
     */
    public void setDstCityName(String dstCityName) {
        this.dstCityName = dstCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.change_driver_reason_id
     *
     * @return the value of yopsaas_ride_order_ext.change_driver_reason_id
     *
     * @mbg.generated
     */
    public Integer getChangeDriverReasonId() {
        return changeDriverReasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.change_driver_reason_id
     *
     * @param changeDriverReasonId the value for yopsaas_ride_order_ext.change_driver_reason_id
     *
     * @mbg.generated
     */
    public void setChangeDriverReasonId(Integer changeDriverReasonId) {
        this.changeDriverReasonId = changeDriverReasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.before_cancel_status
     *
     * @return the value of yopsaas_ride_order_ext.before_cancel_status
     *
     * @mbg.generated
     */
    public Byte getBeforeCancelStatus() {
        return beforeCancelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.before_cancel_status
     *
     * @param beforeCancelStatus the value for yopsaas_ride_order_ext.before_cancel_status
     *
     * @mbg.generated
     */
    public void setBeforeCancelStatus(Byte beforeCancelStatus) {
        this.beforeCancelStatus = beforeCancelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.app_version
     *
     * @return the value of yopsaas_ride_order_ext.app_version
     *
     * @mbg.generated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.app_version
     *
     * @param appVersion the value for yopsaas_ride_order_ext.app_version
     *
     * @mbg.generated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.driver_version
     *
     * @return the value of yopsaas_ride_order_ext.driver_version
     *
     * @mbg.generated
     */
    public String getDriverVersion() {
        return driverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.driver_version
     *
     * @param driverVersion the value for yopsaas_ride_order_ext.driver_version
     *
     * @mbg.generated
     */
    public void setDriverVersion(String driverVersion) {
        this.driverVersion = driverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.balance_time
     *
     * @return the value of yopsaas_ride_order_ext.balance_time
     *
     * @mbg.generated
     */
    public Integer getBalanceTime() {
        return balanceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.balance_time
     *
     * @param balanceTime the value for yopsaas_ride_order_ext.balance_time
     *
     * @mbg.generated
     */
    public void setBalanceTime(Integer balanceTime) {
        this.balanceTime = balanceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.balance_result
     *
     * @return the value of yopsaas_ride_order_ext.balance_result
     *
     * @mbg.generated
     */
    public Byte getBalanceResult() {
        return balanceResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.balance_result
     *
     * @param balanceResult the value for yopsaas_ride_order_ext.balance_result
     *
     * @mbg.generated
     */
    public void setBalanceResult(Byte balanceResult) {
        this.balanceResult = balanceResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.preauth_status
     *
     * @return the value of yopsaas_ride_order_ext.preauth_status
     *
     * @mbg.generated
     */
    public Byte getPreauthStatus() {
        return preauthStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.preauth_status
     *
     * @param preauthStatus the value for yopsaas_ride_order_ext.preauth_status
     *
     * @mbg.generated
     */
    public void setPreauthStatus(Byte preauthStatus) {
        this.preauthStatus = preauthStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.extra_amount
     *
     * @return the value of yopsaas_ride_order_ext.extra_amount
     *
     * @mbg.generated
     */
    public BigDecimal getExtraAmount() {
        return extraAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.extra_amount
     *
     * @param extraAmount the value for yopsaas_ride_order_ext.extra_amount
     *
     * @mbg.generated
     */
    public void setExtraAmount(BigDecimal extraAmount) {
        this.extraAmount = extraAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.predict_amount
     *
     * @return the value of yopsaas_ride_order_ext.predict_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPredictAmount() {
        return predictAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.predict_amount
     *
     * @param predictAmount the value for yopsaas_ride_order_ext.predict_amount
     *
     * @mbg.generated
     */
    public void setPredictAmount(BigDecimal predictAmount) {
        this.predictAmount = predictAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.night_amount
     *
     * @return the value of yopsaas_ride_order_ext.night_amount
     *
     * @mbg.generated
     */
    public BigDecimal getNightAmount() {
        return nightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.night_amount
     *
     * @param nightAmount the value for yopsaas_ride_order_ext.night_amount
     *
     * @mbg.generated
     */
    public void setNightAmount(BigDecimal nightAmount) {
        this.nightAmount = nightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.driver_amount
     *
     * @return the value of yopsaas_ride_order_ext.driver_amount
     *
     * @mbg.generated
     */
    public BigDecimal getDriverAmount() {
        return driverAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.driver_amount
     *
     * @param driverAmount the value for yopsaas_ride_order_ext.driver_amount
     *
     * @mbg.generated
     */
    public void setDriverAmount(BigDecimal driverAmount) {
        this.driverAmount = driverAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.predict_origin_amount
     *
     * @return the value of yopsaas_ride_order_ext.predict_origin_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPredictOriginAmount() {
        return predictOriginAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.predict_origin_amount
     *
     * @param predictOriginAmount the value for yopsaas_ride_order_ext.predict_origin_amount
     *
     * @mbg.generated
     */
    public void setPredictOriginAmount(BigDecimal predictOriginAmount) {
        this.predictOriginAmount = predictOriginAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.predict_pay_amount
     *
     * @return the value of yopsaas_ride_order_ext.predict_pay_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPredictPayAmount() {
        return predictPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.predict_pay_amount
     *
     * @param predictPayAmount the value for yopsaas_ride_order_ext.predict_pay_amount
     *
     * @mbg.generated
     */
    public void setPredictPayAmount(BigDecimal predictPayAmount) {
        this.predictPayAmount = predictPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.additional_time_amount
     *
     * @return the value of yopsaas_ride_order_ext.additional_time_amount
     *
     * @mbg.generated
     */
    public BigDecimal getAdditionalTimeAmount() {
        return additionalTimeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.additional_time_amount
     *
     * @param additionalTimeAmount the value for yopsaas_ride_order_ext.additional_time_amount
     *
     * @mbg.generated
     */
    public void setAdditionalTimeAmount(BigDecimal additionalTimeAmount) {
        this.additionalTimeAmount = additionalTimeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.highway_amount
     *
     * @return the value of yopsaas_ride_order_ext.highway_amount
     *
     * @mbg.generated
     */
    public BigDecimal getHighwayAmount() {
        return highwayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.highway_amount
     *
     * @param highwayAmount the value for yopsaas_ride_order_ext.highway_amount
     *
     * @mbg.generated
     */
    public void setHighwayAmount(BigDecimal highwayAmount) {
        this.highwayAmount = highwayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.parking_amount
     *
     * @return the value of yopsaas_ride_order_ext.parking_amount
     *
     * @mbg.generated
     */
    public BigDecimal getParkingAmount() {
        return parkingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.parking_amount
     *
     * @param parkingAmount the value for yopsaas_ride_order_ext.parking_amount
     *
     * @mbg.generated
     */
    public void setParkingAmount(BigDecimal parkingAmount) {
        this.parkingAmount = parkingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.addons_amount
     *
     * @return the value of yopsaas_ride_order_ext.addons_amount
     *
     * @mbg.generated
     */
    public BigDecimal getAddonsAmount() {
        return addonsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.addons_amount
     *
     * @param addonsAmount the value for yopsaas_ride_order_ext.addons_amount
     *
     * @mbg.generated
     */
    public void setAddonsAmount(BigDecimal addonsAmount) {
        this.addonsAmount = addonsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.addons_amount_src
     *
     * @return the value of yopsaas_ride_order_ext.addons_amount_src
     *
     * @mbg.generated
     */
    public String getAddonsAmountSrc() {
        return addonsAmountSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.addons_amount_src
     *
     * @param addonsAmountSrc the value for yopsaas_ride_order_ext.addons_amount_src
     *
     * @mbg.generated
     */
    public void setAddonsAmountSrc(String addonsAmountSrc) {
        this.addonsAmountSrc = addonsAmountSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.other_amount
     *
     * @return the value of yopsaas_ride_order_ext.other_amount
     *
     * @mbg.generated
     */
    public BigDecimal getOtherAmount() {
        return otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.other_amount
     *
     * @param otherAmount the value for yopsaas_ride_order_ext.other_amount
     *
     * @mbg.generated
     */
    public void setOtherAmount(BigDecimal otherAmount) {
        this.otherAmount = otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.runtime
     *
     * @return the value of yopsaas_ride_order_ext.runtime
     *
     * @mbg.generated
     */
    public Integer getRuntime() {
        return runtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.runtime
     *
     * @param runtime the value for yopsaas_ride_order_ext.runtime
     *
     * @mbg.generated
     */
    public void setRuntime(Integer runtime) {
        this.runtime = runtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.total_distance
     *
     * @return the value of yopsaas_ride_order_ext.total_distance
     *
     * @mbg.generated
     */
    public Integer getTotalDistance() {
        return totalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.total_distance
     *
     * @param totalDistance the value for yopsaas_ride_order_ext.total_distance
     *
     * @mbg.generated
     */
    public void setTotalDistance(Integer totalDistance) {
        this.totalDistance = totalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.deadhead_distance
     *
     * @return the value of yopsaas_ride_order_ext.deadhead_distance
     *
     * @mbg.generated
     */
    public Integer getDeadheadDistance() {
        return deadheadDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.deadhead_distance
     *
     * @param deadheadDistance the value for yopsaas_ride_order_ext.deadhead_distance
     *
     * @mbg.generated
     */
    public void setDeadheadDistance(Integer deadheadDistance) {
        this.deadheadDistance = deadheadDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.is_night
     *
     * @return the value of yopsaas_ride_order_ext.is_night
     *
     * @mbg.generated
     */
    public Byte getIsNight() {
        return isNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.is_night
     *
     * @param isNight the value for yopsaas_ride_order_ext.is_night
     *
     * @mbg.generated
     */
    public void setIsNight(Byte isNight) {
        this.isNight = isNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.regulatepan_amount
     *
     * @return the value of yopsaas_ride_order_ext.regulatepan_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRegulatepanAmount() {
        return regulatepanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.regulatepan_amount
     *
     * @param regulatepanAmount the value for yopsaas_ride_order_ext.regulatepan_amount
     *
     * @mbg.generated
     */
    public void setRegulatepanAmount(BigDecimal regulatepanAmount) {
        this.regulatepanAmount = regulatepanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.regulatedri_amount
     *
     * @return the value of yopsaas_ride_order_ext.regulatedri_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRegulatedriAmount() {
        return regulatedriAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.regulatedri_amount
     *
     * @param regulatedriAmount the value for yopsaas_ride_order_ext.regulatedri_amount
     *
     * @mbg.generated
     */
    public void setRegulatedriAmount(BigDecimal regulatedriAmount) {
        this.regulatedriAmount = regulatedriAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.regulatepan_reason
     *
     * @return the value of yopsaas_ride_order_ext.regulatepan_reason
     *
     * @mbg.generated
     */
    public String getRegulatepanReason() {
        return regulatepanReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.regulatepan_reason
     *
     * @param regulatepanReason the value for yopsaas_ride_order_ext.regulatepan_reason
     *
     * @mbg.generated
     */
    public void setRegulatepanReason(String regulatepanReason) {
        this.regulatepanReason = regulatepanReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.regulatedri_reason
     *
     * @return the value of yopsaas_ride_order_ext.regulatedri_reason
     *
     * @mbg.generated
     */
    public String getRegulatedriReason() {
        return regulatedriReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.regulatedri_reason
     *
     * @param regulatedriReason the value for yopsaas_ride_order_ext.regulatedri_reason
     *
     * @mbg.generated
     */
    public void setRegulatedriReason(String regulatedriReason) {
        this.regulatedriReason = regulatedriReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.regulate_amount
     *
     * @return the value of yopsaas_ride_order_ext.regulate_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRegulateAmount() {
        return regulateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.regulate_amount
     *
     * @param regulateAmount the value for yopsaas_ride_order_ext.regulate_amount
     *
     * @mbg.generated
     */
    public void setRegulateAmount(BigDecimal regulateAmount) {
        this.regulateAmount = regulateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.estimate_snap
     *
     * @return the value of yopsaas_ride_order_ext.estimate_snap
     *
     * @mbg.generated
     */
    public String getEstimateSnap() {
        return estimateSnap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.estimate_snap
     *
     * @param estimateSnap the value for yopsaas_ride_order_ext.estimate_snap
     *
     * @mbg.generated
     */
    public void setEstimateSnap(String estimateSnap) {
        this.estimateSnap = estimateSnap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.order_port
     *
     * @return the value of yopsaas_ride_order_ext.order_port
     *
     * @mbg.generated
     */
    public Integer getOrderPort() {
        return orderPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.order_port
     *
     * @param orderPort the value for yopsaas_ride_order_ext.order_port
     *
     * @mbg.generated
     */
    public void setOrderPort(Integer orderPort) {
        this.orderPort = orderPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.update_time
     *
     * @return the value of yopsaas_ride_order_ext.update_time
     *
     * @mbg.generated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.update_time
     *
     * @param updateTime the value for yopsaas_ride_order_ext.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rideOrderId=").append(rideOrderId);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", userType=").append(userType);
        sb.append(", sms=").append(sms);
        sb.append(", createOrderLongitude=").append(createOrderLongitude);
        sb.append(", createOrderLatitude=").append(createOrderLatitude);
        sb.append(", confirmLatitude=").append(confirmLatitude);
        sb.append(", confirmLongitude=").append(confirmLongitude);
        sb.append(", arriveLatitude=").append(arriveLatitude);
        sb.append(", arriveLongitude=").append(arriveLongitude);
        sb.append(", srcCityName=").append(srcCityName);
        sb.append(", dstCityName=").append(dstCityName);
        sb.append(", changeDriverReasonId=").append(changeDriverReasonId);
        sb.append(", beforeCancelStatus=").append(beforeCancelStatus);
        sb.append(", appVersion=").append(appVersion);
        sb.append(", driverVersion=").append(driverVersion);
        sb.append(", balanceTime=").append(balanceTime);
        sb.append(", balanceResult=").append(balanceResult);
        sb.append(", preauthStatus=").append(preauthStatus);
        sb.append(", extraAmount=").append(extraAmount);
        sb.append(", predictAmount=").append(predictAmount);
        sb.append(", nightAmount=").append(nightAmount);
        sb.append(", driverAmount=").append(driverAmount);
        sb.append(", predictOriginAmount=").append(predictOriginAmount);
        sb.append(", predictPayAmount=").append(predictPayAmount);
        sb.append(", additionalTimeAmount=").append(additionalTimeAmount);
        sb.append(", highwayAmount=").append(highwayAmount);
        sb.append(", parkingAmount=").append(parkingAmount);
        sb.append(", addonsAmount=").append(addonsAmount);
        sb.append(", addonsAmountSrc=").append(addonsAmountSrc);
        sb.append(", otherAmount=").append(otherAmount);
        sb.append(", runtime=").append(runtime);
        sb.append(", totalDistance=").append(totalDistance);
        sb.append(", deadheadDistance=").append(deadheadDistance);
        sb.append(", isNight=").append(isNight);
        sb.append(", regulatepanAmount=").append(regulatepanAmount);
        sb.append(", regulatedriAmount=").append(regulatedriAmount);
        sb.append(", regulatepanReason=").append(regulatepanReason);
        sb.append(", regulatedriReason=").append(regulatedriReason);
        sb.append(", regulateAmount=").append(regulateAmount);
        sb.append(", estimateSnap=").append(estimateSnap);
        sb.append(", orderPort=").append(orderPort);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YopsaasRideOrderExt other = (YopsaasRideOrderExt) that;
        return (this.getRideOrderId() == null ? other.getRideOrderId() == null : this.getRideOrderId().equals(other.getRideOrderId()))
            && (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()))
            && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
            && (this.getSms() == null ? other.getSms() == null : this.getSms().equals(other.getSms()))
            && (this.getCreateOrderLongitude() == null ? other.getCreateOrderLongitude() == null : this.getCreateOrderLongitude().equals(other.getCreateOrderLongitude()))
            && (this.getCreateOrderLatitude() == null ? other.getCreateOrderLatitude() == null : this.getCreateOrderLatitude().equals(other.getCreateOrderLatitude()))
            && (this.getConfirmLatitude() == null ? other.getConfirmLatitude() == null : this.getConfirmLatitude().equals(other.getConfirmLatitude()))
            && (this.getConfirmLongitude() == null ? other.getConfirmLongitude() == null : this.getConfirmLongitude().equals(other.getConfirmLongitude()))
            && (this.getArriveLatitude() == null ? other.getArriveLatitude() == null : this.getArriveLatitude().equals(other.getArriveLatitude()))
            && (this.getArriveLongitude() == null ? other.getArriveLongitude() == null : this.getArriveLongitude().equals(other.getArriveLongitude()))
            && (this.getSrcCityName() == null ? other.getSrcCityName() == null : this.getSrcCityName().equals(other.getSrcCityName()))
            && (this.getDstCityName() == null ? other.getDstCityName() == null : this.getDstCityName().equals(other.getDstCityName()))
            && (this.getChangeDriverReasonId() == null ? other.getChangeDriverReasonId() == null : this.getChangeDriverReasonId().equals(other.getChangeDriverReasonId()))
            && (this.getBeforeCancelStatus() == null ? other.getBeforeCancelStatus() == null : this.getBeforeCancelStatus().equals(other.getBeforeCancelStatus()))
            && (this.getAppVersion() == null ? other.getAppVersion() == null : this.getAppVersion().equals(other.getAppVersion()))
            && (this.getDriverVersion() == null ? other.getDriverVersion() == null : this.getDriverVersion().equals(other.getDriverVersion()))
            && (this.getBalanceTime() == null ? other.getBalanceTime() == null : this.getBalanceTime().equals(other.getBalanceTime()))
            && (this.getBalanceResult() == null ? other.getBalanceResult() == null : this.getBalanceResult().equals(other.getBalanceResult()))
            && (this.getPreauthStatus() == null ? other.getPreauthStatus() == null : this.getPreauthStatus().equals(other.getPreauthStatus()))
            && (this.getExtraAmount() == null ? other.getExtraAmount() == null : this.getExtraAmount().equals(other.getExtraAmount()))
            && (this.getPredictAmount() == null ? other.getPredictAmount() == null : this.getPredictAmount().equals(other.getPredictAmount()))
            && (this.getNightAmount() == null ? other.getNightAmount() == null : this.getNightAmount().equals(other.getNightAmount()))
            && (this.getDriverAmount() == null ? other.getDriverAmount() == null : this.getDriverAmount().equals(other.getDriverAmount()))
            && (this.getPredictOriginAmount() == null ? other.getPredictOriginAmount() == null : this.getPredictOriginAmount().equals(other.getPredictOriginAmount()))
            && (this.getPredictPayAmount() == null ? other.getPredictPayAmount() == null : this.getPredictPayAmount().equals(other.getPredictPayAmount()))
            && (this.getAdditionalTimeAmount() == null ? other.getAdditionalTimeAmount() == null : this.getAdditionalTimeAmount().equals(other.getAdditionalTimeAmount()))
            && (this.getHighwayAmount() == null ? other.getHighwayAmount() == null : this.getHighwayAmount().equals(other.getHighwayAmount()))
            && (this.getParkingAmount() == null ? other.getParkingAmount() == null : this.getParkingAmount().equals(other.getParkingAmount()))
            && (this.getAddonsAmount() == null ? other.getAddonsAmount() == null : this.getAddonsAmount().equals(other.getAddonsAmount()))
            && (this.getAddonsAmountSrc() == null ? other.getAddonsAmountSrc() == null : this.getAddonsAmountSrc().equals(other.getAddonsAmountSrc()))
            && (this.getOtherAmount() == null ? other.getOtherAmount() == null : this.getOtherAmount().equals(other.getOtherAmount()))
            && (this.getRuntime() == null ? other.getRuntime() == null : this.getRuntime().equals(other.getRuntime()))
            && (this.getTotalDistance() == null ? other.getTotalDistance() == null : this.getTotalDistance().equals(other.getTotalDistance()))
            && (this.getDeadheadDistance() == null ? other.getDeadheadDistance() == null : this.getDeadheadDistance().equals(other.getDeadheadDistance()))
            && (this.getIsNight() == null ? other.getIsNight() == null : this.getIsNight().equals(other.getIsNight()))
            && (this.getRegulatepanAmount() == null ? other.getRegulatepanAmount() == null : this.getRegulatepanAmount().equals(other.getRegulatepanAmount()))
            && (this.getRegulatedriAmount() == null ? other.getRegulatedriAmount() == null : this.getRegulatedriAmount().equals(other.getRegulatedriAmount()))
            && (this.getRegulatepanReason() == null ? other.getRegulatepanReason() == null : this.getRegulatepanReason().equals(other.getRegulatepanReason()))
            && (this.getRegulatedriReason() == null ? other.getRegulatedriReason() == null : this.getRegulatedriReason().equals(other.getRegulatedriReason()))
            && (this.getRegulateAmount() == null ? other.getRegulateAmount() == null : this.getRegulateAmount().equals(other.getRegulateAmount()))
            && (this.getEstimateSnap() == null ? other.getEstimateSnap() == null : this.getEstimateSnap().equals(other.getEstimateSnap()))
            && (this.getOrderPort() == null ? other.getOrderPort() == null : this.getOrderPort().equals(other.getOrderPort()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRideOrderId() == null) ? 0 : getRideOrderId().hashCode());
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getSms() == null) ? 0 : getSms().hashCode());
        result = prime * result + ((getCreateOrderLongitude() == null) ? 0 : getCreateOrderLongitude().hashCode());
        result = prime * result + ((getCreateOrderLatitude() == null) ? 0 : getCreateOrderLatitude().hashCode());
        result = prime * result + ((getConfirmLatitude() == null) ? 0 : getConfirmLatitude().hashCode());
        result = prime * result + ((getConfirmLongitude() == null) ? 0 : getConfirmLongitude().hashCode());
        result = prime * result + ((getArriveLatitude() == null) ? 0 : getArriveLatitude().hashCode());
        result = prime * result + ((getArriveLongitude() == null) ? 0 : getArriveLongitude().hashCode());
        result = prime * result + ((getSrcCityName() == null) ? 0 : getSrcCityName().hashCode());
        result = prime * result + ((getDstCityName() == null) ? 0 : getDstCityName().hashCode());
        result = prime * result + ((getChangeDriverReasonId() == null) ? 0 : getChangeDriverReasonId().hashCode());
        result = prime * result + ((getBeforeCancelStatus() == null) ? 0 : getBeforeCancelStatus().hashCode());
        result = prime * result + ((getAppVersion() == null) ? 0 : getAppVersion().hashCode());
        result = prime * result + ((getDriverVersion() == null) ? 0 : getDriverVersion().hashCode());
        result = prime * result + ((getBalanceTime() == null) ? 0 : getBalanceTime().hashCode());
        result = prime * result + ((getBalanceResult() == null) ? 0 : getBalanceResult().hashCode());
        result = prime * result + ((getPreauthStatus() == null) ? 0 : getPreauthStatus().hashCode());
        result = prime * result + ((getExtraAmount() == null) ? 0 : getExtraAmount().hashCode());
        result = prime * result + ((getPredictAmount() == null) ? 0 : getPredictAmount().hashCode());
        result = prime * result + ((getNightAmount() == null) ? 0 : getNightAmount().hashCode());
        result = prime * result + ((getDriverAmount() == null) ? 0 : getDriverAmount().hashCode());
        result = prime * result + ((getPredictOriginAmount() == null) ? 0 : getPredictOriginAmount().hashCode());
        result = prime * result + ((getPredictPayAmount() == null) ? 0 : getPredictPayAmount().hashCode());
        result = prime * result + ((getAdditionalTimeAmount() == null) ? 0 : getAdditionalTimeAmount().hashCode());
        result = prime * result + ((getHighwayAmount() == null) ? 0 : getHighwayAmount().hashCode());
        result = prime * result + ((getParkingAmount() == null) ? 0 : getParkingAmount().hashCode());
        result = prime * result + ((getAddonsAmount() == null) ? 0 : getAddonsAmount().hashCode());
        result = prime * result + ((getAddonsAmountSrc() == null) ? 0 : getAddonsAmountSrc().hashCode());
        result = prime * result + ((getOtherAmount() == null) ? 0 : getOtherAmount().hashCode());
        result = prime * result + ((getRuntime() == null) ? 0 : getRuntime().hashCode());
        result = prime * result + ((getTotalDistance() == null) ? 0 : getTotalDistance().hashCode());
        result = prime * result + ((getDeadheadDistance() == null) ? 0 : getDeadheadDistance().hashCode());
        result = prime * result + ((getIsNight() == null) ? 0 : getIsNight().hashCode());
        result = prime * result + ((getRegulatepanAmount() == null) ? 0 : getRegulatepanAmount().hashCode());
        result = prime * result + ((getRegulatedriAmount() == null) ? 0 : getRegulatedriAmount().hashCode());
        result = prime * result + ((getRegulatepanReason() == null) ? 0 : getRegulatepanReason().hashCode());
        result = prime * result + ((getRegulatedriReason() == null) ? 0 : getRegulatedriReason().hashCode());
        result = prime * result + ((getRegulateAmount() == null) ? 0 : getRegulateAmount().hashCode());
        result = prime * result + ((getEstimateSnap() == null) ? 0 : getEstimateSnap().hashCode());
        result = prime * result + ((getOrderPort() == null) ? 0 : getOrderPort().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    public enum Column {
        rideOrderId("ride_order_id", "rideOrderId", "BIGINT", false),
        operatorId("operator_id", "operatorId", "INTEGER", false),
        userType("user_type", "userType", "TINYINT", false),
        sms("sms", "sms", "INTEGER", false),
        createOrderLongitude("create_order_longitude", "createOrderLongitude", "DOUBLE", false),
        createOrderLatitude("create_order_latitude", "createOrderLatitude", "DOUBLE", false),
        confirmLatitude("confirm_latitude", "confirmLatitude", "DOUBLE", false),
        confirmLongitude("confirm_longitude", "confirmLongitude", "DOUBLE", false),
        arriveLatitude("arrive_latitude", "arriveLatitude", "DOUBLE", false),
        arriveLongitude("arrive_longitude", "arriveLongitude", "DOUBLE", false),
        srcCityName("src_city_name", "srcCityName", "VARCHAR", false),
        dstCityName("dst_city_name", "dstCityName", "VARCHAR", false),
        changeDriverReasonId("change_driver_reason_id", "changeDriverReasonId", "INTEGER", false),
        beforeCancelStatus("before_cancel_status", "beforeCancelStatus", "TINYINT", false),
        appVersion("app_version", "appVersion", "VARCHAR", false),
        driverVersion("driver_version", "driverVersion", "VARCHAR", false),
        balanceTime("balance_time", "balanceTime", "INTEGER", false),
        balanceResult("balance_result", "balanceResult", "TINYINT", false),
        preauthStatus("preauth_status", "preauthStatus", "TINYINT", false),
        extraAmount("extra_amount", "extraAmount", "DECIMAL", false),
        predictAmount("predict_amount", "predictAmount", "DECIMAL", false),
        nightAmount("night_amount", "nightAmount", "DECIMAL", false),
        driverAmount("driver_amount", "driverAmount", "DECIMAL", false),
        predictOriginAmount("predict_origin_amount", "predictOriginAmount", "DECIMAL", false),
        predictPayAmount("predict_pay_amount", "predictPayAmount", "DECIMAL", false),
        additionalTimeAmount("additional_time_amount", "additionalTimeAmount", "DECIMAL", false),
        highwayAmount("highway_amount", "highwayAmount", "DECIMAL", false),
        parkingAmount("parking_amount", "parkingAmount", "DECIMAL", false),
        addonsAmount("addons_amount", "addonsAmount", "DECIMAL", false),
        addonsAmountSrc("addons_amount_src", "addonsAmountSrc", "VARCHAR", false),
        otherAmount("other_amount", "otherAmount", "DECIMAL", false),
        runtime("runtime", "runtime", "INTEGER", false),
        totalDistance("total_distance", "totalDistance", "INTEGER", false),
        deadheadDistance("deadhead_distance", "deadheadDistance", "INTEGER", false),
        isNight("is_night", "isNight", "TINYINT", false),
        regulatepanAmount("regulatepan_amount", "regulatepanAmount", "DECIMAL", false),
        regulatedriAmount("regulatedri_amount", "regulatedriAmount", "DECIMAL", false),
        regulatepanReason("regulatepan_reason", "regulatepanReason", "VARCHAR", false),
        regulatedriReason("regulatedri_reason", "regulatedriReason", "VARCHAR", false),
        regulateAmount("regulate_amount", "regulateAmount", "DECIMAL", false),
        estimateSnap("estimate_snap", "estimateSnap", "VARCHAR", false),
        orderPort("order_port", "orderPort", "INTEGER", false),
        updateTime("update_time", "updateTime", "INTEGER", false),
        destCity("dest_city", "destCity", "VARBINARY", false),
        dispatchDriverIds("dispatch_driver_ids", "dispatchDriverIds", "VARBINARY", false),
        appMsg("app_msg", "appMsg", "LONGVARCHAR", false),
        comment("comment", "comment", "LONGVARCHAR", true),
        ip("ip", "ip", "VARBINARY", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}