package com.yongche.yopsaas.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class YopsaasRideOrderExtWithBLOBs extends YopsaasRideOrderExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.dest_city
     *
     * @mbg.generated
     */
    private byte[] destCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.dispatch_driver_ids
     *
     * @mbg.generated
     */
    private byte[] dispatchDriverIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.app_msg
     *
     * @mbg.generated
     */
    private String appMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_ext.ip
     *
     * @mbg.generated
     */
    private byte[] ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.dest_city
     *
     * @return the value of yopsaas_ride_order_ext.dest_city
     *
     * @mbg.generated
     */
    public byte[] getDestCity() {
        return destCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.dest_city
     *
     * @param destCity the value for yopsaas_ride_order_ext.dest_city
     *
     * @mbg.generated
     */
    public void setDestCity(byte[] destCity) {
        this.destCity = destCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.dispatch_driver_ids
     *
     * @return the value of yopsaas_ride_order_ext.dispatch_driver_ids
     *
     * @mbg.generated
     */
    public byte[] getDispatchDriverIds() {
        return dispatchDriverIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.dispatch_driver_ids
     *
     * @param dispatchDriverIds the value for yopsaas_ride_order_ext.dispatch_driver_ids
     *
     * @mbg.generated
     */
    public void setDispatchDriverIds(byte[] dispatchDriverIds) {
        this.dispatchDriverIds = dispatchDriverIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.app_msg
     *
     * @return the value of yopsaas_ride_order_ext.app_msg
     *
     * @mbg.generated
     */
    public String getAppMsg() {
        return appMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.app_msg
     *
     * @param appMsg the value for yopsaas_ride_order_ext.app_msg
     *
     * @mbg.generated
     */
    public void setAppMsg(String appMsg) {
        this.appMsg = appMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.comment
     *
     * @return the value of yopsaas_ride_order_ext.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.comment
     *
     * @param comment the value for yopsaas_ride_order_ext.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_ext.ip
     *
     * @return the value of yopsaas_ride_order_ext.ip
     *
     * @mbg.generated
     */
    public byte[] getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_ext.ip
     *
     * @param ip the value for yopsaas_ride_order_ext.ip
     *
     * @mbg.generated
     */
    public void setIp(byte[] ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", destCity=").append(destCity);
        sb.append(", dispatchDriverIds=").append(dispatchDriverIds);
        sb.append(", appMsg=").append(appMsg);
        sb.append(", comment=").append(comment);
        sb.append(", ip=").append(ip);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YopsaasRideOrderExtWithBLOBs other = (YopsaasRideOrderExtWithBLOBs) that;
        return (this.getRideOrderId() == null ? other.getRideOrderId() == null : this.getRideOrderId().equals(other.getRideOrderId()))
            && (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()))
            && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
            && (this.getSms() == null ? other.getSms() == null : this.getSms().equals(other.getSms()))
            && (this.getCreateOrderLongitude() == null ? other.getCreateOrderLongitude() == null : this.getCreateOrderLongitude().equals(other.getCreateOrderLongitude()))
            && (this.getCreateOrderLatitude() == null ? other.getCreateOrderLatitude() == null : this.getCreateOrderLatitude().equals(other.getCreateOrderLatitude()))
            && (this.getConfirmLatitude() == null ? other.getConfirmLatitude() == null : this.getConfirmLatitude().equals(other.getConfirmLatitude()))
            && (this.getConfirmLongitude() == null ? other.getConfirmLongitude() == null : this.getConfirmLongitude().equals(other.getConfirmLongitude()))
            && (this.getArriveLatitude() == null ? other.getArriveLatitude() == null : this.getArriveLatitude().equals(other.getArriveLatitude()))
            && (this.getArriveLongitude() == null ? other.getArriveLongitude() == null : this.getArriveLongitude().equals(other.getArriveLongitude()))
            && (this.getSrcCityName() == null ? other.getSrcCityName() == null : this.getSrcCityName().equals(other.getSrcCityName()))
            && (this.getDstCityName() == null ? other.getDstCityName() == null : this.getDstCityName().equals(other.getDstCityName()))
            && (this.getChangeDriverReasonId() == null ? other.getChangeDriverReasonId() == null : this.getChangeDriverReasonId().equals(other.getChangeDriverReasonId()))
            && (this.getBeforeCancelStatus() == null ? other.getBeforeCancelStatus() == null : this.getBeforeCancelStatus().equals(other.getBeforeCancelStatus()))
            && (this.getAppVersion() == null ? other.getAppVersion() == null : this.getAppVersion().equals(other.getAppVersion()))
            && (this.getDriverVersion() == null ? other.getDriverVersion() == null : this.getDriverVersion().equals(other.getDriverVersion()))
            && (this.getBalanceTime() == null ? other.getBalanceTime() == null : this.getBalanceTime().equals(other.getBalanceTime()))
            && (this.getBalanceResult() == null ? other.getBalanceResult() == null : this.getBalanceResult().equals(other.getBalanceResult()))
            && (this.getPreauthStatus() == null ? other.getPreauthStatus() == null : this.getPreauthStatus().equals(other.getPreauthStatus()))
            && (this.getExtraAmount() == null ? other.getExtraAmount() == null : this.getExtraAmount().equals(other.getExtraAmount()))
            && (this.getPredictAmount() == null ? other.getPredictAmount() == null : this.getPredictAmount().equals(other.getPredictAmount()))
            && (this.getNightAmount() == null ? other.getNightAmount() == null : this.getNightAmount().equals(other.getNightAmount()))
            && (this.getDriverAmount() == null ? other.getDriverAmount() == null : this.getDriverAmount().equals(other.getDriverAmount()))
            && (this.getPredictOriginAmount() == null ? other.getPredictOriginAmount() == null : this.getPredictOriginAmount().equals(other.getPredictOriginAmount()))
            && (this.getPredictPayAmount() == null ? other.getPredictPayAmount() == null : this.getPredictPayAmount().equals(other.getPredictPayAmount()))
            && (this.getAdditionalTimeAmount() == null ? other.getAdditionalTimeAmount() == null : this.getAdditionalTimeAmount().equals(other.getAdditionalTimeAmount()))
            && (this.getHighwayAmount() == null ? other.getHighwayAmount() == null : this.getHighwayAmount().equals(other.getHighwayAmount()))
            && (this.getParkingAmount() == null ? other.getParkingAmount() == null : this.getParkingAmount().equals(other.getParkingAmount()))
            && (this.getAddonsAmount() == null ? other.getAddonsAmount() == null : this.getAddonsAmount().equals(other.getAddonsAmount()))
            && (this.getAddonsAmountSrc() == null ? other.getAddonsAmountSrc() == null : this.getAddonsAmountSrc().equals(other.getAddonsAmountSrc()))
            && (this.getOtherAmount() == null ? other.getOtherAmount() == null : this.getOtherAmount().equals(other.getOtherAmount()))
            && (this.getRuntime() == null ? other.getRuntime() == null : this.getRuntime().equals(other.getRuntime()))
            && (this.getTotalDistance() == null ? other.getTotalDistance() == null : this.getTotalDistance().equals(other.getTotalDistance()))
            && (this.getDeadheadDistance() == null ? other.getDeadheadDistance() == null : this.getDeadheadDistance().equals(other.getDeadheadDistance()))
            && (this.getIsNight() == null ? other.getIsNight() == null : this.getIsNight().equals(other.getIsNight()))
            && (this.getRegulatepanAmount() == null ? other.getRegulatepanAmount() == null : this.getRegulatepanAmount().equals(other.getRegulatepanAmount()))
            && (this.getRegulatedriAmount() == null ? other.getRegulatedriAmount() == null : this.getRegulatedriAmount().equals(other.getRegulatedriAmount()))
            && (this.getRegulatepanReason() == null ? other.getRegulatepanReason() == null : this.getRegulatepanReason().equals(other.getRegulatepanReason()))
            && (this.getRegulatedriReason() == null ? other.getRegulatedriReason() == null : this.getRegulatedriReason().equals(other.getRegulatedriReason()))
            && (this.getRegulateAmount() == null ? other.getRegulateAmount() == null : this.getRegulateAmount().equals(other.getRegulateAmount()))
            && (this.getEstimateSnap() == null ? other.getEstimateSnap() == null : this.getEstimateSnap().equals(other.getEstimateSnap()))
            && (this.getOrderPort() == null ? other.getOrderPort() == null : this.getOrderPort().equals(other.getOrderPort()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (Arrays.equals(this.getDestCity(), other.getDestCity()))
            && (Arrays.equals(this.getDispatchDriverIds(), other.getDispatchDriverIds()))
            && (this.getAppMsg() == null ? other.getAppMsg() == null : this.getAppMsg().equals(other.getAppMsg()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (Arrays.equals(this.getIp(), other.getIp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRideOrderId() == null) ? 0 : getRideOrderId().hashCode());
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getSms() == null) ? 0 : getSms().hashCode());
        result = prime * result + ((getCreateOrderLongitude() == null) ? 0 : getCreateOrderLongitude().hashCode());
        result = prime * result + ((getCreateOrderLatitude() == null) ? 0 : getCreateOrderLatitude().hashCode());
        result = prime * result + ((getConfirmLatitude() == null) ? 0 : getConfirmLatitude().hashCode());
        result = prime * result + ((getConfirmLongitude() == null) ? 0 : getConfirmLongitude().hashCode());
        result = prime * result + ((getArriveLatitude() == null) ? 0 : getArriveLatitude().hashCode());
        result = prime * result + ((getArriveLongitude() == null) ? 0 : getArriveLongitude().hashCode());
        result = prime * result + ((getSrcCityName() == null) ? 0 : getSrcCityName().hashCode());
        result = prime * result + ((getDstCityName() == null) ? 0 : getDstCityName().hashCode());
        result = prime * result + ((getChangeDriverReasonId() == null) ? 0 : getChangeDriverReasonId().hashCode());
        result = prime * result + ((getBeforeCancelStatus() == null) ? 0 : getBeforeCancelStatus().hashCode());
        result = prime * result + ((getAppVersion() == null) ? 0 : getAppVersion().hashCode());
        result = prime * result + ((getDriverVersion() == null) ? 0 : getDriverVersion().hashCode());
        result = prime * result + ((getBalanceTime() == null) ? 0 : getBalanceTime().hashCode());
        result = prime * result + ((getBalanceResult() == null) ? 0 : getBalanceResult().hashCode());
        result = prime * result + ((getPreauthStatus() == null) ? 0 : getPreauthStatus().hashCode());
        result = prime * result + ((getExtraAmount() == null) ? 0 : getExtraAmount().hashCode());
        result = prime * result + ((getPredictAmount() == null) ? 0 : getPredictAmount().hashCode());
        result = prime * result + ((getNightAmount() == null) ? 0 : getNightAmount().hashCode());
        result = prime * result + ((getDriverAmount() == null) ? 0 : getDriverAmount().hashCode());
        result = prime * result + ((getPredictOriginAmount() == null) ? 0 : getPredictOriginAmount().hashCode());
        result = prime * result + ((getPredictPayAmount() == null) ? 0 : getPredictPayAmount().hashCode());
        result = prime * result + ((getAdditionalTimeAmount() == null) ? 0 : getAdditionalTimeAmount().hashCode());
        result = prime * result + ((getHighwayAmount() == null) ? 0 : getHighwayAmount().hashCode());
        result = prime * result + ((getParkingAmount() == null) ? 0 : getParkingAmount().hashCode());
        result = prime * result + ((getAddonsAmount() == null) ? 0 : getAddonsAmount().hashCode());
        result = prime * result + ((getAddonsAmountSrc() == null) ? 0 : getAddonsAmountSrc().hashCode());
        result = prime * result + ((getOtherAmount() == null) ? 0 : getOtherAmount().hashCode());
        result = prime * result + ((getRuntime() == null) ? 0 : getRuntime().hashCode());
        result = prime * result + ((getTotalDistance() == null) ? 0 : getTotalDistance().hashCode());
        result = prime * result + ((getDeadheadDistance() == null) ? 0 : getDeadheadDistance().hashCode());
        result = prime * result + ((getIsNight() == null) ? 0 : getIsNight().hashCode());
        result = prime * result + ((getRegulatepanAmount() == null) ? 0 : getRegulatepanAmount().hashCode());
        result = prime * result + ((getRegulatedriAmount() == null) ? 0 : getRegulatedriAmount().hashCode());
        result = prime * result + ((getRegulatepanReason() == null) ? 0 : getRegulatepanReason().hashCode());
        result = prime * result + ((getRegulatedriReason() == null) ? 0 : getRegulatedriReason().hashCode());
        result = prime * result + ((getRegulateAmount() == null) ? 0 : getRegulateAmount().hashCode());
        result = prime * result + ((getEstimateSnap() == null) ? 0 : getEstimateSnap().hashCode());
        result = prime * result + ((getOrderPort() == null) ? 0 : getOrderPort().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + (Arrays.hashCode(getDestCity()));
        result = prime * result + (Arrays.hashCode(getDispatchDriverIds()));
        result = prime * result + ((getAppMsg() == null) ? 0 : getAppMsg().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + (Arrays.hashCode(getIp()));
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    public enum Column {
        rideOrderId("ride_order_id", "rideOrderId", "BIGINT", false),
        operatorId("operator_id", "operatorId", "INTEGER", false),
        userType("user_type", "userType", "TINYINT", false),
        sms("sms", "sms", "INTEGER", false),
        createOrderLongitude("create_order_longitude", "createOrderLongitude", "DOUBLE", false),
        createOrderLatitude("create_order_latitude", "createOrderLatitude", "DOUBLE", false),
        confirmLatitude("confirm_latitude", "confirmLatitude", "DOUBLE", false),
        confirmLongitude("confirm_longitude", "confirmLongitude", "DOUBLE", false),
        arriveLatitude("arrive_latitude", "arriveLatitude", "DOUBLE", false),
        arriveLongitude("arrive_longitude", "arriveLongitude", "DOUBLE", false),
        srcCityName("src_city_name", "srcCityName", "VARCHAR", false),
        dstCityName("dst_city_name", "dstCityName", "VARCHAR", false),
        changeDriverReasonId("change_driver_reason_id", "changeDriverReasonId", "INTEGER", false),
        beforeCancelStatus("before_cancel_status", "beforeCancelStatus", "TINYINT", false),
        appVersion("app_version", "appVersion", "VARCHAR", false),
        driverVersion("driver_version", "driverVersion", "VARCHAR", false),
        balanceTime("balance_time", "balanceTime", "INTEGER", false),
        balanceResult("balance_result", "balanceResult", "TINYINT", false),
        preauthStatus("preauth_status", "preauthStatus", "TINYINT", false),
        extraAmount("extra_amount", "extraAmount", "DECIMAL", false),
        predictAmount("predict_amount", "predictAmount", "DECIMAL", false),
        nightAmount("night_amount", "nightAmount", "DECIMAL", false),
        driverAmount("driver_amount", "driverAmount", "DECIMAL", false),
        predictOriginAmount("predict_origin_amount", "predictOriginAmount", "DECIMAL", false),
        predictPayAmount("predict_pay_amount", "predictPayAmount", "DECIMAL", false),
        additionalTimeAmount("additional_time_amount", "additionalTimeAmount", "DECIMAL", false),
        highwayAmount("highway_amount", "highwayAmount", "DECIMAL", false),
        parkingAmount("parking_amount", "parkingAmount", "DECIMAL", false),
        addonsAmount("addons_amount", "addonsAmount", "DECIMAL", false),
        addonsAmountSrc("addons_amount_src", "addonsAmountSrc", "VARCHAR", false),
        otherAmount("other_amount", "otherAmount", "DECIMAL", false),
        runtime("runtime", "runtime", "INTEGER", false),
        totalDistance("total_distance", "totalDistance", "INTEGER", false),
        deadheadDistance("deadhead_distance", "deadheadDistance", "INTEGER", false),
        isNight("is_night", "isNight", "TINYINT", false),
        regulatepanAmount("regulatepan_amount", "regulatepanAmount", "DECIMAL", false),
        regulatedriAmount("regulatedri_amount", "regulatedriAmount", "DECIMAL", false),
        regulatepanReason("regulatepan_reason", "regulatepanReason", "VARCHAR", false),
        regulatedriReason("regulatedri_reason", "regulatedriReason", "VARCHAR", false),
        regulateAmount("regulate_amount", "regulateAmount", "DECIMAL", false),
        estimateSnap("estimate_snap", "estimateSnap", "VARCHAR", false),
        orderPort("order_port", "orderPort", "INTEGER", false),
        updateTime("update_time", "updateTime", "INTEGER", false),
        destCity("dest_city", "destCity", "VARBINARY", false),
        dispatchDriverIds("dispatch_driver_ids", "dispatchDriverIds", "VARBINARY", false),
        appMsg("app_msg", "appMsg", "LONGVARCHAR", false),
        comment("comment", "comment", "LONGVARCHAR", true),
        ip("ip", "ip", "VARBINARY", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_ext
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}