package com.yongche.yopsaas.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class YopsaasRideOrderWithBLOBs extends YopsaasRideOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order.user_phone
     *
     * @mbg.generated
     */
    private byte[] userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order.passenger_phone
     *
     * @mbg.generated
     */
    private byte[] passengerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order.city
     *
     * @mbg.generated
     */
    private byte[] city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order.flight_number
     *
     * @mbg.generated
     */
    private byte[] flightNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order.car_type_ids
     *
     * @mbg.generated
     */
    private byte[] carTypeIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order.driver_phone
     *
     * @mbg.generated
     */
    private byte[] driverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order.passenger_session_id
     *
     * @mbg.generated
     */
    private byte[] passengerSessionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order.user_phone
     *
     * @return the value of yopsaas_ride_order.user_phone
     *
     * @mbg.generated
     */
    public byte[] getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order.user_phone
     *
     * @param userPhone the value for yopsaas_ride_order.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(byte[] userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order.passenger_phone
     *
     * @return the value of yopsaas_ride_order.passenger_phone
     *
     * @mbg.generated
     */
    public byte[] getPassengerPhone() {
        return passengerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order.passenger_phone
     *
     * @param passengerPhone the value for yopsaas_ride_order.passenger_phone
     *
     * @mbg.generated
     */
    public void setPassengerPhone(byte[] passengerPhone) {
        this.passengerPhone = passengerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order.city
     *
     * @return the value of yopsaas_ride_order.city
     *
     * @mbg.generated
     */
    public byte[] getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order.city
     *
     * @param city the value for yopsaas_ride_order.city
     *
     * @mbg.generated
     */
    public void setCity(byte[] city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order.flight_number
     *
     * @return the value of yopsaas_ride_order.flight_number
     *
     * @mbg.generated
     */
    public byte[] getFlightNumber() {
        return flightNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order.flight_number
     *
     * @param flightNumber the value for yopsaas_ride_order.flight_number
     *
     * @mbg.generated
     */
    public void setFlightNumber(byte[] flightNumber) {
        this.flightNumber = flightNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order.car_type_ids
     *
     * @return the value of yopsaas_ride_order.car_type_ids
     *
     * @mbg.generated
     */
    public byte[] getCarTypeIds() {
        return carTypeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order.car_type_ids
     *
     * @param carTypeIds the value for yopsaas_ride_order.car_type_ids
     *
     * @mbg.generated
     */
    public void setCarTypeIds(byte[] carTypeIds) {
        this.carTypeIds = carTypeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order.driver_phone
     *
     * @return the value of yopsaas_ride_order.driver_phone
     *
     * @mbg.generated
     */
    public byte[] getDriverPhone() {
        return driverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order.driver_phone
     *
     * @param driverPhone the value for yopsaas_ride_order.driver_phone
     *
     * @mbg.generated
     */
    public void setDriverPhone(byte[] driverPhone) {
        this.driverPhone = driverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order.passenger_session_id
     *
     * @return the value of yopsaas_ride_order.passenger_session_id
     *
     * @mbg.generated
     */
    public byte[] getPassengerSessionId() {
        return passengerSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order.passenger_session_id
     *
     * @param passengerSessionId the value for yopsaas_ride_order.passenger_session_id
     *
     * @mbg.generated
     */
    public void setPassengerSessionId(byte[] passengerSessionId) {
        this.passengerSessionId = passengerSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userPhone=").append(userPhone);
        sb.append(", passengerPhone=").append(passengerPhone);
        sb.append(", city=").append(city);
        sb.append(", flightNumber=").append(flightNumber);
        sb.append(", carTypeIds=").append(carTypeIds);
        sb.append(", driverPhone=").append(driverPhone);
        sb.append(", passengerSessionId=").append(passengerSessionId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YopsaasRideOrderWithBLOBs other = (YopsaasRideOrderWithBLOBs) that;
        return (this.getRideOrderId() == null ? other.getRideOrderId() == null : this.getRideOrderId().equals(other.getRideOrderId()))
            && (this.getProductTypeId() == null ? other.getProductTypeId() == null : this.getProductTypeId().equals(other.getProductTypeId()))
            && (this.getFixedProductId() == null ? other.getFixedProductId() == null : this.getFixedProductId().equals(other.getFixedProductId()))
            && (this.getIsAsap() == null ? other.getIsAsap() == null : this.getIsAsap().equals(other.getIsAsap()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getPlatform() == null ? other.getPlatform() == null : this.getPlatform().equals(other.getPlatform()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRcStatus() == null ? other.getRcStatus() == null : this.getRcStatus().equals(other.getRcStatus()))
            && (this.getEndStatus() == null ? other.getEndStatus() == null : this.getEndStatus().equals(other.getEndStatus()))
            && (this.getAbnormalMark() == null ? other.getAbnormalMark() == null : this.getAbnormalMark().equals(other.getAbnormalMark()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(other.getAccountId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getPassengerName() == null ? other.getPassengerName() == null : this.getPassengerName().equals(other.getPassengerName()))
            && (this.getCorporateId() == null ? other.getCorporateId() == null : this.getCorporateId().equals(other.getCorporateId()))
            && (this.getCorporateDeptId() == null ? other.getCorporateDeptId() == null : this.getCorporateDeptId().equals(other.getCorporateDeptId()))
            && (this.getReasonId() == null ? other.getReasonId() == null : this.getReasonId().equals(other.getReasonId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getInitTime() == null ? other.getInitTime() == null : this.getInitTime().equals(other.getInitTime()))
            && (this.getSelectCarTime() == null ? other.getSelectCarTime() == null : this.getSelectCarTime().equals(other.getSelectCarTime()))
            && (this.getArrivalTime() == null ? other.getArrivalTime() == null : this.getArrivalTime().equals(other.getArrivalTime()))
            && (this.getCancelTime() == null ? other.getCancelTime() == null : this.getCancelTime().equals(other.getCancelTime()))
            && (this.getCarId() == null ? other.getCarId() == null : this.getCarId().equals(other.getCarId()))
            && (this.getCarTypeId() == null ? other.getCarTypeId() == null : this.getCarTypeId().equals(other.getCarTypeId()))
            && (this.getCarType() == null ? other.getCarType() == null : this.getCarType().equals(other.getCarType()))
            && (this.getCarBrand() == null ? other.getCarBrand() == null : this.getCarBrand().equals(other.getCarBrand()))
            && (this.getDriverId() == null ? other.getDriverId() == null : this.getDriverId().equals(other.getDriverId()))
            && (this.getDriverName() == null ? other.getDriverName() == null : this.getDriverName().equals(other.getDriverName()))
            && (this.getVehicleNumber() == null ? other.getVehicleNumber() == null : this.getVehicleNumber().equals(other.getVehicleNumber()))
            && (this.getExpectStartTime() == null ? other.getExpectStartTime() == null : this.getExpectStartTime().equals(other.getExpectStartTime()))
            && (this.getExpectEndTime() == null ? other.getExpectEndTime() == null : this.getExpectEndTime().equals(other.getExpectEndTime()))
            && (this.getTimeLength() == null ? other.getTimeLength() == null : this.getTimeLength().equals(other.getTimeLength()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getConfirmTime() == null ? other.getConfirmTime() == null : this.getConfirmTime().equals(other.getConfirmTime()))
            && (this.getStartPosition() == null ? other.getStartPosition() == null : this.getStartPosition().equals(other.getStartPosition()))
            && (this.getStartAddress() == null ? other.getStartAddress() == null : this.getStartAddress().equals(other.getStartAddress()))
            && (this.getEndPosition() == null ? other.getEndPosition() == null : this.getEndPosition().equals(other.getEndPosition()))
            && (this.getEndAddress() == null ? other.getEndAddress() == null : this.getEndAddress().equals(other.getEndAddress()))
            && (this.getExpectStartLatitude() == null ? other.getExpectStartLatitude() == null : this.getExpectStartLatitude().equals(other.getExpectStartLatitude()))
            && (this.getExpectStartLongitude() == null ? other.getExpectStartLongitude() == null : this.getExpectStartLongitude().equals(other.getExpectStartLongitude()))
            && (this.getExpectEndLatitude() == null ? other.getExpectEndLatitude() == null : this.getExpectEndLatitude().equals(other.getExpectEndLatitude()))
            && (this.getExpectEndLongitude() == null ? other.getExpectEndLongitude() == null : this.getExpectEndLongitude().equals(other.getExpectEndLongitude()))
            && (this.getStartLatitude() == null ? other.getStartLatitude() == null : this.getStartLatitude().equals(other.getStartLatitude()))
            && (this.getStartLongitude() == null ? other.getStartLongitude() == null : this.getStartLongitude().equals(other.getStartLongitude()))
            && (this.getEndLatitude() == null ? other.getEndLatitude() == null : this.getEndLatitude().equals(other.getEndLatitude()))
            && (this.getEndLongitude() == null ? other.getEndLongitude() == null : this.getEndLongitude().equals(other.getEndLongitude()))
            && (this.getPayment() == null ? other.getPayment() == null : this.getPayment().equals(other.getPayment()))
            && (this.getPayStatus() == null ? other.getPayStatus() == null : this.getPayStatus().equals(other.getPayStatus()))
            && (this.getFirstRechargeTransactionId() == null ? other.getFirstRechargeTransactionId() == null : this.getFirstRechargeTransactionId().equals(other.getFirstRechargeTransactionId()))
            && (this.getFirstRechargeAmount() == null ? other.getFirstRechargeAmount() == null : this.getFirstRechargeAmount().equals(other.getFirstRechargeAmount()))
            && (this.getCouponMemberId() == null ? other.getCouponMemberId() == null : this.getCouponMemberId().equals(other.getCouponMemberId()))
            && (this.getCouponName() == null ? other.getCouponName() == null : this.getCouponName().equals(other.getCouponName()))
            && (this.getCouponType() == null ? other.getCouponType() == null : this.getCouponType().equals(other.getCouponType()))
            && (this.getCouponFacevalue() == null ? other.getCouponFacevalue() == null : this.getCouponFacevalue().equals(other.getCouponFacevalue()))
            && (this.getDiscount() == null ? other.getDiscount() == null : this.getDiscount().equals(other.getDiscount()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getFeeVersion() == null ? other.getFeeVersion() == null : this.getFeeVersion().equals(other.getFeeVersion()))
            && (this.getRefundStatus() == null ? other.getRefundStatus() == null : this.getRefundStatus().equals(other.getRefundStatus()))
            && (this.getPayMethod() == null ? other.getPayMethod() == null : this.getPayMethod().equals(other.getPayMethod()))
            && (this.getBalanceStatus() == null ? other.getBalanceStatus() == null : this.getBalanceStatus().equals(other.getBalanceStatus()))
            && (this.getPayable() == null ? other.getPayable() == null : this.getPayable().equals(other.getPayable()))
            && (this.getTotalAmount() == null ? other.getTotalAmount() == null : this.getTotalAmount().equals(other.getTotalAmount()))
            && (this.getDeposit() == null ? other.getDeposit() == null : this.getDeposit().equals(other.getDeposit()))
            && (this.getLoanInCredit() == null ? other.getLoanInCredit() == null : this.getLoanInCredit().equals(other.getLoanInCredit()))
            && (this.getPayAmount() == null ? other.getPayAmount() == null : this.getPayAmount().equals(other.getPayAmount()))
            && (this.getMinAmount() == null ? other.getMinAmount() == null : this.getMinAmount().equals(other.getMinAmount()))
            && (this.getOriginAmount() == null ? other.getOriginAmount() == null : this.getOriginAmount().equals(other.getOriginAmount()))
            && (this.getOriginSharingAmount() == null ? other.getOriginSharingAmount() == null : this.getOriginSharingAmount().equals(other.getOriginSharingAmount()))
            && (this.getSharingAmount() == null ? other.getSharingAmount() == null : this.getSharingAmount().equals(other.getSharingAmount()))
            && (this.getActualTimeLength() == null ? other.getActualTimeLength() == null : this.getActualTimeLength().equals(other.getActualTimeLength()))
            && (this.getDependableDistance() == null ? other.getDependableDistance() == null : this.getDependableDistance().equals(other.getDependableDistance()))
            && (this.getMileage() == null ? other.getMileage() == null : this.getMileage().equals(other.getMileage()))
            && (this.getSystemDistance() == null ? other.getSystemDistance() == null : this.getSystemDistance().equals(other.getSystemDistance()))
            && (this.getAlitongxinSecretNoX() == null ? other.getAlitongxinSecretNoX() == null : this.getAlitongxinSecretNoX().equals(other.getAlitongxinSecretNoX()))
            && (this.getAlitongxinSubsId() == null ? other.getAlitongxinSubsId() == null : this.getAlitongxinSubsId().equals(other.getAlitongxinSubsId()))
            && (this.getAlitongxinStatus() == null ? other.getAlitongxinStatus() == null : this.getAlitongxinStatus().equals(other.getAlitongxinStatus()))
            && (this.getLastOperator() == null ? other.getLastOperator() == null : this.getLastOperator().equals(other.getLastOperator()))
            && (Arrays.equals(this.getUserPhone(), other.getUserPhone()))
            && (Arrays.equals(this.getPassengerPhone(), other.getPassengerPhone()))
            && (Arrays.equals(this.getCity(), other.getCity()))
            && (Arrays.equals(this.getFlightNumber(), other.getFlightNumber()))
            && (Arrays.equals(this.getCarTypeIds(), other.getCarTypeIds()))
            && (Arrays.equals(this.getDriverPhone(), other.getDriverPhone()))
            && (Arrays.equals(this.getPassengerSessionId(), other.getPassengerSessionId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRideOrderId() == null) ? 0 : getRideOrderId().hashCode());
        result = prime * result + ((getProductTypeId() == null) ? 0 : getProductTypeId().hashCode());
        result = prime * result + ((getFixedProductId() == null) ? 0 : getFixedProductId().hashCode());
        result = prime * result + ((getIsAsap() == null) ? 0 : getIsAsap().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getPlatform() == null) ? 0 : getPlatform().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRcStatus() == null) ? 0 : getRcStatus().hashCode());
        result = prime * result + ((getEndStatus() == null) ? 0 : getEndStatus().hashCode());
        result = prime * result + ((getAbnormalMark() == null) ? 0 : getAbnormalMark().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getPassengerName() == null) ? 0 : getPassengerName().hashCode());
        result = prime * result + ((getCorporateId() == null) ? 0 : getCorporateId().hashCode());
        result = prime * result + ((getCorporateDeptId() == null) ? 0 : getCorporateDeptId().hashCode());
        result = prime * result + ((getReasonId() == null) ? 0 : getReasonId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getInitTime() == null) ? 0 : getInitTime().hashCode());
        result = prime * result + ((getSelectCarTime() == null) ? 0 : getSelectCarTime().hashCode());
        result = prime * result + ((getArrivalTime() == null) ? 0 : getArrivalTime().hashCode());
        result = prime * result + ((getCancelTime() == null) ? 0 : getCancelTime().hashCode());
        result = prime * result + ((getCarId() == null) ? 0 : getCarId().hashCode());
        result = prime * result + ((getCarTypeId() == null) ? 0 : getCarTypeId().hashCode());
        result = prime * result + ((getCarType() == null) ? 0 : getCarType().hashCode());
        result = prime * result + ((getCarBrand() == null) ? 0 : getCarBrand().hashCode());
        result = prime * result + ((getDriverId() == null) ? 0 : getDriverId().hashCode());
        result = prime * result + ((getDriverName() == null) ? 0 : getDriverName().hashCode());
        result = prime * result + ((getVehicleNumber() == null) ? 0 : getVehicleNumber().hashCode());
        result = prime * result + ((getExpectStartTime() == null) ? 0 : getExpectStartTime().hashCode());
        result = prime * result + ((getExpectEndTime() == null) ? 0 : getExpectEndTime().hashCode());
        result = prime * result + ((getTimeLength() == null) ? 0 : getTimeLength().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getConfirmTime() == null) ? 0 : getConfirmTime().hashCode());
        result = prime * result + ((getStartPosition() == null) ? 0 : getStartPosition().hashCode());
        result = prime * result + ((getStartAddress() == null) ? 0 : getStartAddress().hashCode());
        result = prime * result + ((getEndPosition() == null) ? 0 : getEndPosition().hashCode());
        result = prime * result + ((getEndAddress() == null) ? 0 : getEndAddress().hashCode());
        result = prime * result + ((getExpectStartLatitude() == null) ? 0 : getExpectStartLatitude().hashCode());
        result = prime * result + ((getExpectStartLongitude() == null) ? 0 : getExpectStartLongitude().hashCode());
        result = prime * result + ((getExpectEndLatitude() == null) ? 0 : getExpectEndLatitude().hashCode());
        result = prime * result + ((getExpectEndLongitude() == null) ? 0 : getExpectEndLongitude().hashCode());
        result = prime * result + ((getStartLatitude() == null) ? 0 : getStartLatitude().hashCode());
        result = prime * result + ((getStartLongitude() == null) ? 0 : getStartLongitude().hashCode());
        result = prime * result + ((getEndLatitude() == null) ? 0 : getEndLatitude().hashCode());
        result = prime * result + ((getEndLongitude() == null) ? 0 : getEndLongitude().hashCode());
        result = prime * result + ((getPayment() == null) ? 0 : getPayment().hashCode());
        result = prime * result + ((getPayStatus() == null) ? 0 : getPayStatus().hashCode());
        result = prime * result + ((getFirstRechargeTransactionId() == null) ? 0 : getFirstRechargeTransactionId().hashCode());
        result = prime * result + ((getFirstRechargeAmount() == null) ? 0 : getFirstRechargeAmount().hashCode());
        result = prime * result + ((getCouponMemberId() == null) ? 0 : getCouponMemberId().hashCode());
        result = prime * result + ((getCouponName() == null) ? 0 : getCouponName().hashCode());
        result = prime * result + ((getCouponType() == null) ? 0 : getCouponType().hashCode());
        result = prime * result + ((getCouponFacevalue() == null) ? 0 : getCouponFacevalue().hashCode());
        result = prime * result + ((getDiscount() == null) ? 0 : getDiscount().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getFeeVersion() == null) ? 0 : getFeeVersion().hashCode());
        result = prime * result + ((getRefundStatus() == null) ? 0 : getRefundStatus().hashCode());
        result = prime * result + ((getPayMethod() == null) ? 0 : getPayMethod().hashCode());
        result = prime * result + ((getBalanceStatus() == null) ? 0 : getBalanceStatus().hashCode());
        result = prime * result + ((getPayable() == null) ? 0 : getPayable().hashCode());
        result = prime * result + ((getTotalAmount() == null) ? 0 : getTotalAmount().hashCode());
        result = prime * result + ((getDeposit() == null) ? 0 : getDeposit().hashCode());
        result = prime * result + ((getLoanInCredit() == null) ? 0 : getLoanInCredit().hashCode());
        result = prime * result + ((getPayAmount() == null) ? 0 : getPayAmount().hashCode());
        result = prime * result + ((getMinAmount() == null) ? 0 : getMinAmount().hashCode());
        result = prime * result + ((getOriginAmount() == null) ? 0 : getOriginAmount().hashCode());
        result = prime * result + ((getOriginSharingAmount() == null) ? 0 : getOriginSharingAmount().hashCode());
        result = prime * result + ((getSharingAmount() == null) ? 0 : getSharingAmount().hashCode());
        result = prime * result + ((getActualTimeLength() == null) ? 0 : getActualTimeLength().hashCode());
        result = prime * result + ((getDependableDistance() == null) ? 0 : getDependableDistance().hashCode());
        result = prime * result + ((getMileage() == null) ? 0 : getMileage().hashCode());
        result = prime * result + ((getSystemDistance() == null) ? 0 : getSystemDistance().hashCode());
        result = prime * result + ((getAlitongxinSecretNoX() == null) ? 0 : getAlitongxinSecretNoX().hashCode());
        result = prime * result + ((getAlitongxinSubsId() == null) ? 0 : getAlitongxinSubsId().hashCode());
        result = prime * result + ((getAlitongxinStatus() == null) ? 0 : getAlitongxinStatus().hashCode());
        result = prime * result + ((getLastOperator() == null) ? 0 : getLastOperator().hashCode());
        result = prime * result + (Arrays.hashCode(getUserPhone()));
        result = prime * result + (Arrays.hashCode(getPassengerPhone()));
        result = prime * result + (Arrays.hashCode(getCity()));
        result = prime * result + (Arrays.hashCode(getFlightNumber()));
        result = prime * result + (Arrays.hashCode(getCarTypeIds()));
        result = prime * result + (Arrays.hashCode(getDriverPhone()));
        result = prime * result + (Arrays.hashCode(getPassengerSessionId()));
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    public enum Column {
        rideOrderId("ride_order_id", "rideOrderId", "BIGINT", false),
        productTypeId("product_type_id", "productTypeId", "INTEGER", false),
        fixedProductId("fixed_product_id", "fixedProductId", "INTEGER", false),
        isAsap("is_asap", "isAsap", "TINYINT", false),
        source("source", "source", "INTEGER", true),
        platform("platform", "platform", "TINYINT", false),
        status("status", "status", "TINYINT", true),
        rcStatus("rc_status", "rcStatus", "TINYINT", false),
        endStatus("end_status", "endStatus", "TINYINT", false),
        abnormalMark("abnormal_mark", "abnormalMark", "TINYINT", false),
        flag("flag", "flag", "BIGINT", false),
        accountId("account_id", "accountId", "BIGINT", false),
        userId("user_id", "userId", "BIGINT", false),
        passengerName("passenger_name", "passengerName", "VARCHAR", false),
        corporateId("corporate_id", "corporateId", "BIGINT", false),
        corporateDeptId("corporate_dept_id", "corporateDeptId", "INTEGER", false),
        reasonId("reason_id", "reasonId", "INTEGER", false),
        createTime("create_time", "createTime", "INTEGER", false),
        updateTime("update_time", "updateTime", "INTEGER", false),
        initTime("init_time", "initTime", "INTEGER", false),
        selectCarTime("select_car_time", "selectCarTime", "INTEGER", false),
        arrivalTime("arrival_time", "arrivalTime", "INTEGER", false),
        cancelTime("cancel_time", "cancelTime", "INTEGER", false),
        carId("car_id", "carId", "INTEGER", false),
        carTypeId("car_type_id", "carTypeId", "INTEGER", false),
        carType("car_type", "carType", "VARCHAR", false),
        carBrand("car_brand", "carBrand", "VARCHAR", false),
        driverId("driver_id", "driverId", "INTEGER", false),
        driverName("driver_name", "driverName", "VARCHAR", false),
        vehicleNumber("vehicle_number", "vehicleNumber", "VARCHAR", false),
        expectStartTime("expect_start_time", "expectStartTime", "INTEGER", false),
        expectEndTime("expect_end_time", "expectEndTime", "INTEGER", false),
        timeLength("time_length", "timeLength", "INTEGER", false),
        startTime("start_time", "startTime", "INTEGER", false),
        endTime("end_time", "endTime", "INTEGER", false),
        confirmTime("confirm_time", "confirmTime", "INTEGER", false),
        startPosition("start_position", "startPosition", "VARCHAR", false),
        startAddress("start_address", "startAddress", "VARCHAR", false),
        endPosition("end_position", "endPosition", "VARCHAR", false),
        endAddress("end_address", "endAddress", "VARCHAR", false),
        expectStartLatitude("expect_start_latitude", "expectStartLatitude", "DOUBLE", false),
        expectStartLongitude("expect_start_longitude", "expectStartLongitude", "DOUBLE", false),
        expectEndLatitude("expect_end_latitude", "expectEndLatitude", "DOUBLE", false),
        expectEndLongitude("expect_end_longitude", "expectEndLongitude", "DOUBLE", false),
        startLatitude("start_latitude", "startLatitude", "DOUBLE", false),
        startLongitude("start_longitude", "startLongitude", "DOUBLE", false),
        endLatitude("end_latitude", "endLatitude", "DOUBLE", false),
        endLongitude("end_longitude", "endLongitude", "DOUBLE", false),
        payment("payment", "payment", "INTEGER", false),
        payStatus("pay_status", "payStatus", "TINYINT", false),
        firstRechargeTransactionId("first_recharge_transaction_id", "firstRechargeTransactionId", "BIGINT", false),
        firstRechargeAmount("first_recharge_amount", "firstRechargeAmount", "DECIMAL", false),
        couponMemberId("coupon_member_id", "couponMemberId", "BIGINT", false),
        couponName("coupon_name", "couponName", "VARCHAR", false),
        couponType("coupon_type", "couponType", "TINYINT", false),
        couponFacevalue("coupon_facevalue", "couponFacevalue", "DECIMAL", false),
        discount("discount", "discount", "DECIMAL", false),
        version("version", "version", "INTEGER", false),
        feeVersion("fee_version", "feeVersion", "INTEGER", false),
        refundStatus("refund_status", "refundStatus", "TINYINT", false),
        payMethod("pay_method", "payMethod", "TINYINT", false),
        balanceStatus("balance_status", "balanceStatus", "TINYINT", false),
        payable("payable", "payable", "TINYINT", false),
        totalAmount("total_amount", "totalAmount", "DECIMAL", false),
        deposit("deposit", "deposit", "DECIMAL", false),
        loanInCredit("loan_in_credit", "loanInCredit", "DECIMAL", false),
        payAmount("pay_amount", "payAmount", "DECIMAL", false),
        minAmount("min_amount", "minAmount", "DECIMAL", false),
        originAmount("origin_amount", "originAmount", "DECIMAL", false),
        originSharingAmount("origin_sharing_amount", "originSharingAmount", "DECIMAL", false),
        sharingAmount("sharing_amount", "sharingAmount", "DECIMAL", false),
        actualTimeLength("actual_time_length", "actualTimeLength", "INTEGER", false),
        dependableDistance("dependable_distance", "dependableDistance", "INTEGER", false),
        mileage("mileage", "mileage", "INTEGER", false),
        systemDistance("system_distance", "systemDistance", "INTEGER", false),
        alitongxinSecretNoX("alitongxin_secret_no_x", "alitongxinSecretNoX", "VARCHAR", false),
        alitongxinSubsId("alitongxin_subs_id", "alitongxinSubsId", "BIGINT", false),
        alitongxinStatus("alitongxin_status", "alitongxinStatus", "TINYINT", false),
        lastOperator("last_operator", "lastOperator", "VARCHAR", false),
        userPhone("user_phone", "userPhone", "VARBINARY", false),
        passengerPhone("passenger_phone", "passengerPhone", "VARBINARY", false),
        city("city", "city", "VARBINARY", false),
        flightNumber("flight_number", "flightNumber", "VARBINARY", false),
        carTypeIds("car_type_ids", "carTypeIds", "VARBINARY", false),
        driverPhone("driver_phone", "driverPhone", "VARBINARY", false),
        passengerSessionId("passenger_session_id", "passengerSessionId", "VARBINARY", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}