package com.yongche.yopsaas.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class YopsaasRideOrderKv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_kv.ride_order_id
     *
     * @mbg.generated
     */
    private Long rideOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_kv.k
     *
     * @mbg.generated
     */
    private String k;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_kv.v
     *
     * @mbg.generated
     */
    private String v;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_kv.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_kv.create_time
     *
     * @mbg.generated
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_kv.update_time
     *
     * @mbg.generated
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_kv.ride_order_id
     *
     * @return the value of yopsaas_ride_order_kv.ride_order_id
     *
     * @mbg.generated
     */
    public Long getRideOrderId() {
        return rideOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_kv.ride_order_id
     *
     * @param rideOrderId the value for yopsaas_ride_order_kv.ride_order_id
     *
     * @mbg.generated
     */
    public void setRideOrderId(Long rideOrderId) {
        this.rideOrderId = rideOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_kv.k
     *
     * @return the value of yopsaas_ride_order_kv.k
     *
     * @mbg.generated
     */
    public String getK() {
        return k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_kv.k
     *
     * @param k the value for yopsaas_ride_order_kv.k
     *
     * @mbg.generated
     */
    public void setK(String k) {
        this.k = k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_kv.v
     *
     * @return the value of yopsaas_ride_order_kv.v
     *
     * @mbg.generated
     */
    public String getV() {
        return v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_kv.v
     *
     * @param v the value for yopsaas_ride_order_kv.v
     *
     * @mbg.generated
     */
    public void setV(String v) {
        this.v = v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_kv.type
     *
     * @return the value of yopsaas_ride_order_kv.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_kv.type
     *
     * @param type the value for yopsaas_ride_order_kv.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_kv.create_time
     *
     * @return the value of yopsaas_ride_order_kv.create_time
     *
     * @mbg.generated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_kv.create_time
     *
     * @param createTime the value for yopsaas_ride_order_kv.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_kv.update_time
     *
     * @return the value of yopsaas_ride_order_kv.update_time
     *
     * @mbg.generated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_kv.update_time
     *
     * @param updateTime the value for yopsaas_ride_order_kv.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rideOrderId=").append(rideOrderId);
        sb.append(", k=").append(k);
        sb.append(", v=").append(v);
        sb.append(", type=").append(type);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YopsaasRideOrderKv other = (YopsaasRideOrderKv) that;
        return (this.getRideOrderId() == null ? other.getRideOrderId() == null : this.getRideOrderId().equals(other.getRideOrderId()))
            && (this.getK() == null ? other.getK() == null : this.getK().equals(other.getK()))
            && (this.getV() == null ? other.getV() == null : this.getV().equals(other.getV()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRideOrderId() == null) ? 0 : getRideOrderId().hashCode());
        result = prime * result + ((getK() == null) ? 0 : getK().hashCode());
        result = prime * result + ((getV() == null) ? 0 : getV().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    public enum Column {
        rideOrderId("ride_order_id", "rideOrderId", "BIGINT", false),
        k("k", "k", "VARCHAR", true),
        v("v", "v", "VARCHAR", false),
        type("type", "type", "TINYINT", true),
        createTime("create_time", "createTime", "INTEGER", false),
        updateTime("update_time", "updateTime", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_kv
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}