package com.yongche.yopsaas.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class YopsaasRideOrderDispatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.ride_order_dispatch_id
     *
     * @mbg.generated
     */
    private Long rideOrderDispatchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.ride_order_id
     *
     * @mbg.generated
     */
    private Long rideOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.driver_id
     *
     * @mbg.generated
     */
    private Integer driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.good_comment_rate
     *
     * @mbg.generated
     */
    private Integer goodCommentRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.unittime_complete_count
     *
     * @mbg.generated
     */
    private Integer unittimeCompleteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.is_served
     *
     * @mbg.generated
     */
    private Short isServed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.car_type
     *
     * @mbg.generated
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.car_type_id
     *
     * @mbg.generated
     */
    private Integer carTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.is_default
     *
     * @mbg.generated
     */
    private Short isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yopsaas_ride_order_dispatch.create_time
     *
     * @mbg.generated
     */
    private Integer createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.ride_order_dispatch_id
     *
     * @return the value of yopsaas_ride_order_dispatch.ride_order_dispatch_id
     *
     * @mbg.generated
     */
    public Long getRideOrderDispatchId() {
        return rideOrderDispatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.ride_order_dispatch_id
     *
     * @param rideOrderDispatchId the value for yopsaas_ride_order_dispatch.ride_order_dispatch_id
     *
     * @mbg.generated
     */
    public void setRideOrderDispatchId(Long rideOrderDispatchId) {
        this.rideOrderDispatchId = rideOrderDispatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.ride_order_id
     *
     * @return the value of yopsaas_ride_order_dispatch.ride_order_id
     *
     * @mbg.generated
     */
    public Long getRideOrderId() {
        return rideOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.ride_order_id
     *
     * @param rideOrderId the value for yopsaas_ride_order_dispatch.ride_order_id
     *
     * @mbg.generated
     */
    public void setRideOrderId(Long rideOrderId) {
        this.rideOrderId = rideOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.driver_id
     *
     * @return the value of yopsaas_ride_order_dispatch.driver_id
     *
     * @mbg.generated
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.driver_id
     *
     * @param driverId the value for yopsaas_ride_order_dispatch.driver_id
     *
     * @mbg.generated
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.name
     *
     * @return the value of yopsaas_ride_order_dispatch.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.name
     *
     * @param name the value for yopsaas_ride_order_dispatch.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.score
     *
     * @return the value of yopsaas_ride_order_dispatch.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.score
     *
     * @param score the value for yopsaas_ride_order_dispatch.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.good_comment_rate
     *
     * @return the value of yopsaas_ride_order_dispatch.good_comment_rate
     *
     * @mbg.generated
     */
    public Integer getGoodCommentRate() {
        return goodCommentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.good_comment_rate
     *
     * @param goodCommentRate the value for yopsaas_ride_order_dispatch.good_comment_rate
     *
     * @mbg.generated
     */
    public void setGoodCommentRate(Integer goodCommentRate) {
        this.goodCommentRate = goodCommentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.unittime_complete_count
     *
     * @return the value of yopsaas_ride_order_dispatch.unittime_complete_count
     *
     * @mbg.generated
     */
    public Integer getUnittimeCompleteCount() {
        return unittimeCompleteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.unittime_complete_count
     *
     * @param unittimeCompleteCount the value for yopsaas_ride_order_dispatch.unittime_complete_count
     *
     * @mbg.generated
     */
    public void setUnittimeCompleteCount(Integer unittimeCompleteCount) {
        this.unittimeCompleteCount = unittimeCompleteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.is_served
     *
     * @return the value of yopsaas_ride_order_dispatch.is_served
     *
     * @mbg.generated
     */
    public Short getIsServed() {
        return isServed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.is_served
     *
     * @param isServed the value for yopsaas_ride_order_dispatch.is_served
     *
     * @mbg.generated
     */
    public void setIsServed(Short isServed) {
        this.isServed = isServed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.latitude
     *
     * @return the value of yopsaas_ride_order_dispatch.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.latitude
     *
     * @param latitude the value for yopsaas_ride_order_dispatch.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.longitude
     *
     * @return the value of yopsaas_ride_order_dispatch.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.longitude
     *
     * @param longitude the value for yopsaas_ride_order_dispatch.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.brand
     *
     * @return the value of yopsaas_ride_order_dispatch.brand
     *
     * @mbg.generated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.brand
     *
     * @param brand the value for yopsaas_ride_order_dispatch.brand
     *
     * @mbg.generated
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.car_type
     *
     * @return the value of yopsaas_ride_order_dispatch.car_type
     *
     * @mbg.generated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.car_type
     *
     * @param carType the value for yopsaas_ride_order_dispatch.car_type
     *
     * @mbg.generated
     */
    public void setCarType(String carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.car_type_id
     *
     * @return the value of yopsaas_ride_order_dispatch.car_type_id
     *
     * @mbg.generated
     */
    public Integer getCarTypeId() {
        return carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.car_type_id
     *
     * @param carTypeId the value for yopsaas_ride_order_dispatch.car_type_id
     *
     * @mbg.generated
     */
    public void setCarTypeId(Integer carTypeId) {
        this.carTypeId = carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.is_default
     *
     * @return the value of yopsaas_ride_order_dispatch.is_default
     *
     * @mbg.generated
     */
    public Short getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.is_default
     *
     * @param isDefault the value for yopsaas_ride_order_dispatch.is_default
     *
     * @mbg.generated
     */
    public void setIsDefault(Short isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.photo
     *
     * @return the value of yopsaas_ride_order_dispatch.photo
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.photo
     *
     * @param photo the value for yopsaas_ride_order_dispatch.photo
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.status
     *
     * @return the value of yopsaas_ride_order_dispatch.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.status
     *
     * @param status the value for yopsaas_ride_order_dispatch.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yopsaas_ride_order_dispatch.create_time
     *
     * @return the value of yopsaas_ride_order_dispatch.create_time
     *
     * @mbg.generated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yopsaas_ride_order_dispatch.create_time
     *
     * @param createTime the value for yopsaas_ride_order_dispatch.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rideOrderDispatchId=").append(rideOrderDispatchId);
        sb.append(", rideOrderId=").append(rideOrderId);
        sb.append(", driverId=").append(driverId);
        sb.append(", name=").append(name);
        sb.append(", score=").append(score);
        sb.append(", goodCommentRate=").append(goodCommentRate);
        sb.append(", unittimeCompleteCount=").append(unittimeCompleteCount);
        sb.append(", isServed=").append(isServed);
        sb.append(", latitude=").append(latitude);
        sb.append(", longitude=").append(longitude);
        sb.append(", brand=").append(brand);
        sb.append(", carType=").append(carType);
        sb.append(", carTypeId=").append(carTypeId);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", photo=").append(photo);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YopsaasRideOrderDispatch other = (YopsaasRideOrderDispatch) that;
        return (this.getRideOrderDispatchId() == null ? other.getRideOrderDispatchId() == null : this.getRideOrderDispatchId().equals(other.getRideOrderDispatchId()))
            && (this.getRideOrderId() == null ? other.getRideOrderId() == null : this.getRideOrderId().equals(other.getRideOrderId()))
            && (this.getDriverId() == null ? other.getDriverId() == null : this.getDriverId().equals(other.getDriverId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getGoodCommentRate() == null ? other.getGoodCommentRate() == null : this.getGoodCommentRate().equals(other.getGoodCommentRate()))
            && (this.getUnittimeCompleteCount() == null ? other.getUnittimeCompleteCount() == null : this.getUnittimeCompleteCount().equals(other.getUnittimeCompleteCount()))
            && (this.getIsServed() == null ? other.getIsServed() == null : this.getIsServed().equals(other.getIsServed()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getBrand() == null ? other.getBrand() == null : this.getBrand().equals(other.getBrand()))
            && (this.getCarType() == null ? other.getCarType() == null : this.getCarType().equals(other.getCarType()))
            && (this.getCarTypeId() == null ? other.getCarTypeId() == null : this.getCarTypeId().equals(other.getCarTypeId()))
            && (this.getIsDefault() == null ? other.getIsDefault() == null : this.getIsDefault().equals(other.getIsDefault()))
            && (this.getPhoto() == null ? other.getPhoto() == null : this.getPhoto().equals(other.getPhoto()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRideOrderDispatchId() == null) ? 0 : getRideOrderDispatchId().hashCode());
        result = prime * result + ((getRideOrderId() == null) ? 0 : getRideOrderId().hashCode());
        result = prime * result + ((getDriverId() == null) ? 0 : getDriverId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getGoodCommentRate() == null) ? 0 : getGoodCommentRate().hashCode());
        result = prime * result + ((getUnittimeCompleteCount() == null) ? 0 : getUnittimeCompleteCount().hashCode());
        result = prime * result + ((getIsServed() == null) ? 0 : getIsServed().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getBrand() == null) ? 0 : getBrand().hashCode());
        result = prime * result + ((getCarType() == null) ? 0 : getCarType().hashCode());
        result = prime * result + ((getCarTypeId() == null) ? 0 : getCarTypeId().hashCode());
        result = prime * result + ((getIsDefault() == null) ? 0 : getIsDefault().hashCode());
        result = prime * result + ((getPhoto() == null) ? 0 : getPhoto().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    public enum Column {
        rideOrderDispatchId("ride_order_dispatch_id", "rideOrderDispatchId", "BIGINT", false),
        rideOrderId("ride_order_id", "rideOrderId", "BIGINT", false),
        driverId("driver_id", "driverId", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        score("score", "score", "INTEGER", false),
        goodCommentRate("good_comment_rate", "goodCommentRate", "INTEGER", false),
        unittimeCompleteCount("unittime_complete_count", "unittimeCompleteCount", "INTEGER", false),
        isServed("is_served", "isServed", "SMALLINT", false),
        latitude("latitude", "latitude", "DOUBLE", false),
        longitude("longitude", "longitude", "DOUBLE", false),
        brand("brand", "brand", "VARCHAR", false),
        carType("car_type", "carType", "VARCHAR", false),
        carTypeId("car_type_id", "carTypeId", "INTEGER", false),
        isDefault("is_default", "isDefault", "SMALLINT", false),
        photo("photo", "photo", "VARCHAR", false),
        status("status", "status", "TINYINT", true),
        createTime("create_time", "createTime", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yopsaas_ride_order_dispatch
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}