package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasRideOrder;
import com.yongche.yopsaas.db.domain.YopsaasRideOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasRideOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    long countByExample(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long rideOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int insert(YopsaasRideOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasRideOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    YopsaasRideOrder selectOneByExample(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    YopsaasRideOrder selectOneByExampleSelective(@Param("example") YopsaasRideOrderExample example, @Param("selective") YopsaasRideOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    List<YopsaasRideOrder> selectByExampleSelective(@Param("example") YopsaasRideOrderExample example, @Param("selective") YopsaasRideOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    List<YopsaasRideOrder> selectByExample(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    YopsaasRideOrder selectByPrimaryKeySelective(@Param("rideOrderId") Long rideOrderId, @Param("selective") YopsaasRideOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    YopsaasRideOrder selectByPrimaryKey(Long rideOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasRideOrder record, @Param("example") YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasRideOrder record, @Param("example") YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasRideOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasRideOrder record);
}