package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasSearchHistory;
import com.yongche.yopsaas.db.domain.YopsaasSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    long countByExample(YopsaasSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int insert(YopsaasSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    YopsaasSearchHistory selectOneByExample(YopsaasSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    YopsaasSearchHistory selectOneByExampleSelective(@Param("example") YopsaasSearchHistoryExample example, @Param("selective") YopsaasSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    List<YopsaasSearchHistory> selectByExampleSelective(@Param("example") YopsaasSearchHistoryExample example, @Param("selective") YopsaasSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    List<YopsaasSearchHistory> selectByExample(YopsaasSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    YopsaasSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    YopsaasSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    YopsaasSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasSearchHistory record, @Param("example") YopsaasSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasSearchHistory record, @Param("example") YopsaasSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}