package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasCategory;
import com.yongche.yopsaas.db.domain.YopsaasCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    long countByExample(YopsaasCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int insert(YopsaasCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    YopsaasCategory selectOneByExample(YopsaasCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    YopsaasCategory selectOneByExampleSelective(@Param("example") YopsaasCategoryExample example, @Param("selective") YopsaasCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    List<YopsaasCategory> selectByExampleSelective(@Param("example") YopsaasCategoryExample example, @Param("selective") YopsaasCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    List<YopsaasCategory> selectByExample(YopsaasCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    YopsaasCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    YopsaasCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    YopsaasCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasCategory record, @Param("example") YopsaasCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasCategory record, @Param("example") YopsaasCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}