package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasCollect;
import com.yongche.yopsaas.db.domain.YopsaasCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    long countByExample(YopsaasCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int insert(YopsaasCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    YopsaasCollect selectOneByExample(YopsaasCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    YopsaasCollect selectOneByExampleSelective(@Param("example") YopsaasCollectExample example, @Param("selective") YopsaasCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    List<YopsaasCollect> selectByExampleSelective(@Param("example") YopsaasCollectExample example, @Param("selective") YopsaasCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    List<YopsaasCollect> selectByExample(YopsaasCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    YopsaasCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    YopsaasCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    YopsaasCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasCollect record, @Param("example") YopsaasCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasCollect record, @Param("example") YopsaasCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}