package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasBrand;
import com.yongche.yopsaas.db.domain.YopsaasBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    long countByExample(YopsaasBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int insert(YopsaasBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    YopsaasBrand selectOneByExample(YopsaasBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    YopsaasBrand selectOneByExampleSelective(@Param("example") YopsaasBrandExample example, @Param("selective") YopsaasBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    List<YopsaasBrand> selectByExampleSelective(@Param("example") YopsaasBrandExample example, @Param("selective") YopsaasBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    List<YopsaasBrand> selectByExample(YopsaasBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    YopsaasBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    YopsaasBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    YopsaasBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasBrand record, @Param("example") YopsaasBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasBrand record, @Param("example") YopsaasBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}