package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasOrder;
import com.yongche.yopsaas.db.domain.YopsaasOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    long countByExample(YopsaasOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    int insert(YopsaasOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    YopsaasOrder selectOneByExample(YopsaasOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    YopsaasOrder selectOneByExampleSelective(@Param("example") YopsaasOrderExample example, @Param("selective") YopsaasOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    List<YopsaasOrder> selectByExampleSelective(@Param("example") YopsaasOrderExample example, @Param("selective") YopsaasOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    List<YopsaasOrder> selectByExample(YopsaasOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasOrder record, @Param("example") YopsaasOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasOrder record, @Param("example") YopsaasOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasOrderExample example);
}