package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasRideOrderKv;
import com.yongche.yopsaas.db.domain.YopsaasRideOrderKvExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasRideOrderKvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    long countByExample(YopsaasRideOrderKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasRideOrderKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    int insert(YopsaasRideOrderKv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasRideOrderKv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    YopsaasRideOrderKv selectOneByExample(YopsaasRideOrderKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    YopsaasRideOrderKv selectOneByExampleSelective(@Param("example") YopsaasRideOrderKvExample example, @Param("selective") YopsaasRideOrderKv.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderKv> selectByExampleSelective(@Param("example") YopsaasRideOrderKvExample example, @Param("selective") YopsaasRideOrderKv.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderKv> selectByExample(YopsaasRideOrderKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasRideOrderKv record, @Param("example") YopsaasRideOrderKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_kv
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasRideOrderKv record, @Param("example") YopsaasRideOrderKvExample example);
}