package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasCart;
import com.yongche.yopsaas.db.domain.YopsaasCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    long countByExample(YopsaasCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int insert(YopsaasCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    YopsaasCart selectOneByExample(YopsaasCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    YopsaasCart selectOneByExampleSelective(@Param("example") YopsaasCartExample example, @Param("selective") YopsaasCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    List<YopsaasCart> selectByExampleSelective(@Param("example") YopsaasCartExample example, @Param("selective") YopsaasCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    List<YopsaasCart> selectByExample(YopsaasCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    YopsaasCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    YopsaasCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    YopsaasCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasCart record, @Param("example") YopsaasCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasCart record, @Param("example") YopsaasCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}