package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasTopic;
import com.yongche.yopsaas.db.domain.YopsaasTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    long countByExample(YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int insert(YopsaasTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    YopsaasTopic selectOneByExample(YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    YopsaasTopic selectOneByExampleSelective(@Param("example") YopsaasTopicExample example, @Param("selective") YopsaasTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    YopsaasTopic selectOneByExampleWithBLOBs(YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    List<YopsaasTopic> selectByExampleSelective(@Param("example") YopsaasTopicExample example, @Param("selective") YopsaasTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    List<YopsaasTopic> selectByExampleWithBLOBs(YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    List<YopsaasTopic> selectByExample(YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    YopsaasTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    YopsaasTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    YopsaasTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasTopic record, @Param("example") YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") YopsaasTopic record, @Param("example") YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasTopic record, @Param("example") YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(YopsaasTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}