package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasGroupon;
import com.yongche.yopsaas.db.domain.YopsaasGrouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    long countByExample(YopsaasGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    int insert(YopsaasGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    YopsaasGroupon selectOneByExample(YopsaasGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    YopsaasGroupon selectOneByExampleSelective(@Param("example") YopsaasGrouponExample example, @Param("selective") YopsaasGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    List<YopsaasGroupon> selectByExampleSelective(@Param("example") YopsaasGrouponExample example, @Param("selective") YopsaasGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    List<YopsaasGroupon> selectByExample(YopsaasGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasGroupon record, @Param("example") YopsaasGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasGroupon record, @Param("example") YopsaasGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasGrouponExample example);
}