package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasAdmin;
import com.yongche.yopsaas.db.domain.YopsaasAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    long countByExample(YopsaasAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int insert(YopsaasAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    YopsaasAdmin selectOneByExample(YopsaasAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    YopsaasAdmin selectOneByExampleSelective(@Param("example") YopsaasAdminExample example, @Param("selective") YopsaasAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    List<YopsaasAdmin> selectByExampleSelective(@Param("example") YopsaasAdminExample example, @Param("selective") YopsaasAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    List<YopsaasAdmin> selectByExample(YopsaasAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    YopsaasAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    YopsaasAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    YopsaasAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasAdmin record, @Param("example") YopsaasAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasAdmin record, @Param("example") YopsaasAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}