package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasGoods;
import com.yongche.yopsaas.db.domain.YopsaasGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    long countByExample(YopsaasGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    int insert(YopsaasGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    YopsaasGoods selectOneByExample(YopsaasGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    YopsaasGoods selectOneByExampleSelective(@Param("example") YopsaasGoodsExample example, @Param("selective") YopsaasGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    YopsaasGoods selectOneByExampleWithBLOBs(YopsaasGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    List<YopsaasGoods> selectByExampleSelective(@Param("example") YopsaasGoodsExample example, @Param("selective") YopsaasGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    List<YopsaasGoods> selectByExampleWithBLOBs(YopsaasGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    List<YopsaasGoods> selectByExample(YopsaasGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasGoods record, @Param("example") YopsaasGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") YopsaasGoods record, @Param("example") YopsaasGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasGoods record, @Param("example") YopsaasGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasGoodsExample example);
}