package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasAddress;
import com.yongche.yopsaas.db.domain.YopsaasAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    long countByExample(YopsaasAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    int insert(YopsaasAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    YopsaasAddress selectOneByExample(YopsaasAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    YopsaasAddress selectOneByExampleSelective(@Param("example") YopsaasAddressExample example, @Param("selective") YopsaasAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    List<YopsaasAddress> selectByExampleSelective(@Param("example") YopsaasAddressExample example, @Param("selective") YopsaasAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    List<YopsaasAddress> selectByExample(YopsaasAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasAddress record, @Param("example") YopsaasAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasAddress record, @Param("example") YopsaasAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasAddressExample example);
}