package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasRideOrderExt;
import com.yongche.yopsaas.db.domain.YopsaasRideOrderExtExample;
import com.yongche.yopsaas.db.domain.YopsaasRideOrderExtWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasRideOrderExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    long countByExample(YopsaasRideOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasRideOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    int insert(YopsaasRideOrderExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasRideOrderExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    YopsaasRideOrderExt selectOneByExample(YopsaasRideOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    YopsaasRideOrderExtWithBLOBs selectOneByExampleSelective(@Param("example") YopsaasRideOrderExtExample example, @Param("selective") YopsaasRideOrderExtWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    YopsaasRideOrderExtWithBLOBs selectOneByExampleWithBLOBs(YopsaasRideOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderExtWithBLOBs> selectByExampleSelective(@Param("example") YopsaasRideOrderExtExample example, @Param("selective") YopsaasRideOrderExtWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderExtWithBLOBs> selectByExampleWithBLOBs(YopsaasRideOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderExt> selectByExample(YopsaasRideOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasRideOrderExtWithBLOBs record, @Param("example") YopsaasRideOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") YopsaasRideOrderExtWithBLOBs record, @Param("example") YopsaasRideOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_ext
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasRideOrderExt record, @Param("example") YopsaasRideOrderExtExample example);
}