package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasOrderGoods;
import com.yongche.yopsaas.db.domain.YopsaasOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    long countByExample(YopsaasOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int insert(YopsaasOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    YopsaasOrderGoods selectOneByExample(YopsaasOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    YopsaasOrderGoods selectOneByExampleSelective(@Param("example") YopsaasOrderGoodsExample example, @Param("selective") YopsaasOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    List<YopsaasOrderGoods> selectByExampleSelective(@Param("example") YopsaasOrderGoodsExample example, @Param("selective") YopsaasOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    List<YopsaasOrderGoods> selectByExample(YopsaasOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    YopsaasOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    YopsaasOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    YopsaasOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasOrderGoods record, @Param("example") YopsaasOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasOrderGoods record, @Param("example") YopsaasOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}