package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasAd;
import com.yongche.yopsaas.db.domain.YopsaasAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    long countByExample(YopsaasAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int insert(YopsaasAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    YopsaasAd selectOneByExample(YopsaasAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    YopsaasAd selectOneByExampleSelective(@Param("example") YopsaasAdExample example, @Param("selective") YopsaasAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    List<YopsaasAd> selectByExampleSelective(@Param("example") YopsaasAdExample example, @Param("selective") YopsaasAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    List<YopsaasAd> selectByExample(YopsaasAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    YopsaasAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    YopsaasAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    YopsaasAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasAd record, @Param("example") YopsaasAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasAd record, @Param("example") YopsaasAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}