package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasCoupon;
import com.yongche.yopsaas.db.domain.YopsaasCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    long countByExample(YopsaasCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int insert(YopsaasCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    YopsaasCoupon selectOneByExample(YopsaasCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    YopsaasCoupon selectOneByExampleSelective(@Param("example") YopsaasCouponExample example, @Param("selective") YopsaasCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    List<YopsaasCoupon> selectByExampleSelective(@Param("example") YopsaasCouponExample example, @Param("selective") YopsaasCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    List<YopsaasCoupon> selectByExample(YopsaasCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    YopsaasCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    YopsaasCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    YopsaasCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasCoupon record, @Param("example") YopsaasCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasCoupon record, @Param("example") YopsaasCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}