package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasGoodsSpecification;
import com.yongche.yopsaas.db.domain.YopsaasGoodsSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(YopsaasGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int insert(YopsaasGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    YopsaasGoodsSpecification selectOneByExample(YopsaasGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    YopsaasGoodsSpecification selectOneByExampleSelective(@Param("example") YopsaasGoodsSpecificationExample example, @Param("selective") YopsaasGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    List<YopsaasGoodsSpecification> selectByExampleSelective(@Param("example") YopsaasGoodsSpecificationExample example, @Param("selective") YopsaasGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    List<YopsaasGoodsSpecification> selectByExample(YopsaasGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    YopsaasGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    YopsaasGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    YopsaasGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasGoodsSpecification record, @Param("example") YopsaasGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasGoodsSpecification record, @Param("example") YopsaasGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}