package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasRole;
import com.yongche.yopsaas.db.domain.YopsaasRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    long countByExample(YopsaasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int insert(YopsaasRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    YopsaasRole selectOneByExample(YopsaasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    YopsaasRole selectOneByExampleSelective(@Param("example") YopsaasRoleExample example, @Param("selective") YopsaasRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    List<YopsaasRole> selectByExampleSelective(@Param("example") YopsaasRoleExample example, @Param("selective") YopsaasRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    List<YopsaasRole> selectByExample(YopsaasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    YopsaasRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    YopsaasRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    YopsaasRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasRole record, @Param("example") YopsaasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasRole record, @Param("example") YopsaasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}