package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasRideOrder;
import com.yongche.yopsaas.db.domain.YopsaasRideOrderExample;
import com.yongche.yopsaas.db.domain.YopsaasRideOrderWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasRideOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    long countByExample(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long rideOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int insert(YopsaasRideOrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasRideOrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    YopsaasRideOrder selectOneByExample(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    YopsaasRideOrderWithBLOBs selectOneByExampleSelective(@Param("example") YopsaasRideOrderExample example, @Param("selective") YopsaasRideOrderWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    YopsaasRideOrderWithBLOBs selectOneByExampleWithBLOBs(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderWithBLOBs> selectByExampleSelective(@Param("example") YopsaasRideOrderExample example, @Param("selective") YopsaasRideOrderWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderWithBLOBs> selectByExampleWithBLOBs(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    List<YopsaasRideOrder> selectByExample(YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    YopsaasRideOrderWithBLOBs selectByPrimaryKeySelective(@Param("rideOrderId") Long rideOrderId, @Param("selective") YopsaasRideOrderWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    YopsaasRideOrderWithBLOBs selectByPrimaryKey(Long rideOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasRideOrderWithBLOBs record, @Param("example") YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") YopsaasRideOrderWithBLOBs record, @Param("example") YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasRideOrder record, @Param("example") YopsaasRideOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasRideOrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(YopsaasRideOrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasRideOrder record);
}