package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasFeedback;
import com.yongche.yopsaas.db.domain.YopsaasFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    long countByExample(YopsaasFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    int insert(YopsaasFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    YopsaasFeedback selectOneByExample(YopsaasFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    YopsaasFeedback selectOneByExampleSelective(@Param("example") YopsaasFeedbackExample example, @Param("selective") YopsaasFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    List<YopsaasFeedback> selectByExampleSelective(@Param("example") YopsaasFeedbackExample example, @Param("selective") YopsaasFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    List<YopsaasFeedback> selectByExample(YopsaasFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasFeedback record, @Param("example") YopsaasFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasFeedback record, @Param("example") YopsaasFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasFeedbackExample example);
}