package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasGrouponRules;
import com.yongche.yopsaas.db.domain.YopsaasGrouponRulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(YopsaasGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    int insert(YopsaasGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    YopsaasGrouponRules selectOneByExample(YopsaasGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    YopsaasGrouponRules selectOneByExampleSelective(@Param("example") YopsaasGrouponRulesExample example, @Param("selective") YopsaasGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    List<YopsaasGrouponRules> selectByExampleSelective(@Param("example") YopsaasGrouponRulesExample example, @Param("selective") YopsaasGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    List<YopsaasGrouponRules> selectByExample(YopsaasGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasGrouponRules record, @Param("example") YopsaasGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasGrouponRules record, @Param("example") YopsaasGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasGrouponRulesExample example);
}