package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasGoodsProduct;
import com.yongche.yopsaas.db.domain.YopsaasGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    long countByExample(YopsaasGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int insert(YopsaasGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    YopsaasGoodsProduct selectOneByExample(YopsaasGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    YopsaasGoodsProduct selectOneByExampleSelective(@Param("example") YopsaasGoodsProductExample example, @Param("selective") YopsaasGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    List<YopsaasGoodsProduct> selectByExampleSelective(@Param("example") YopsaasGoodsProductExample example, @Param("selective") YopsaasGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    List<YopsaasGoodsProduct> selectByExample(YopsaasGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    YopsaasGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YopsaasGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    YopsaasGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    YopsaasGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasGoodsProduct record, @Param("example") YopsaasGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasGoodsProduct record, @Param("example") YopsaasGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") YopsaasGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}