package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasRideOrderTransactionHistory;
import com.yongche.yopsaas.db.domain.YopsaasRideOrderTransactionHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasRideOrderTransactionHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    long countByExample(YopsaasRideOrderTransactionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasRideOrderTransactionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long rideOrderTransactionHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    int insert(YopsaasRideOrderTransactionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasRideOrderTransactionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    YopsaasRideOrderTransactionHistory selectOneByExample(YopsaasRideOrderTransactionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    YopsaasRideOrderTransactionHistory selectOneByExampleSelective(@Param("example") YopsaasRideOrderTransactionHistoryExample example, @Param("selective") YopsaasRideOrderTransactionHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderTransactionHistory> selectByExampleSelective(@Param("example") YopsaasRideOrderTransactionHistoryExample example, @Param("selective") YopsaasRideOrderTransactionHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderTransactionHistory> selectByExample(YopsaasRideOrderTransactionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    YopsaasRideOrderTransactionHistory selectByPrimaryKeySelective(@Param("rideOrderTransactionHistoryId") Long rideOrderTransactionHistoryId, @Param("selective") YopsaasRideOrderTransactionHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    YopsaasRideOrderTransactionHistory selectByPrimaryKey(Long rideOrderTransactionHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasRideOrderTransactionHistory record, @Param("example") YopsaasRideOrderTransactionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasRideOrderTransactionHistory record, @Param("example") YopsaasRideOrderTransactionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasRideOrderTransactionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_transaction_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasRideOrderTransactionHistory record);
}