package com.yongche.yopsaas.db.dao;

import com.yongche.yopsaas.db.domain.YopsaasRideOrderDispatch;
import com.yongche.yopsaas.db.domain.YopsaasRideOrderDispatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YopsaasRideOrderDispatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    long countByExample(YopsaasRideOrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    int deleteByExample(YopsaasRideOrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long rideOrderDispatchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    int insert(YopsaasRideOrderDispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    int insertSelective(YopsaasRideOrderDispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    YopsaasRideOrderDispatch selectOneByExample(YopsaasRideOrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    YopsaasRideOrderDispatch selectOneByExampleSelective(@Param("example") YopsaasRideOrderDispatchExample example, @Param("selective") YopsaasRideOrderDispatch.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderDispatch> selectByExampleSelective(@Param("example") YopsaasRideOrderDispatchExample example, @Param("selective") YopsaasRideOrderDispatch.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    List<YopsaasRideOrderDispatch> selectByExample(YopsaasRideOrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    YopsaasRideOrderDispatch selectByPrimaryKeySelective(@Param("rideOrderDispatchId") Long rideOrderDispatchId, @Param("selective") YopsaasRideOrderDispatch.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    YopsaasRideOrderDispatch selectByPrimaryKey(Long rideOrderDispatchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YopsaasRideOrderDispatch record, @Param("example") YopsaasRideOrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YopsaasRideOrderDispatch record, @Param("example") YopsaasRideOrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YopsaasRideOrderDispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yopsaas_ride_order_dispatch
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YopsaasRideOrderDispatch record);
}